### ISSUE TITLE
HTP missing from all fuel tanks

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#105]
Title says it all i think.

**Comment by sswelm** [comment]
Its in the Cryo tanks, but perhaps not under the name you expect, its called H2O2, which is the chemical definition of HydrogenPeroxide

**Comment by alismatales** [comment]
Checked again just to make sure, no HTP, H2O2 or Hydrogen peroxide in the cryo tanks.

HTP is only available in the hex tanks and the arcjet service containers at the moment.

**Comment by arivaldh** [comment]
I'll look into it.

**Comment by arivaldh** [comment]
I wouldn't close it yet.
Old cryogenic tanks did had some discrepancies between them.
But, new TankRevamp is once again missing HTP as a resource. Shouldn't we add it?

**Comment by sswelm** [comment]
Yes add it, even though it is little used. Still its an important resource for ISRU which is the whole reason these tanks are switchable in the first place.

**Comment by arivaldh** [comment]
I personally use HTP. That's the best Electrical Propulsion Fuel that can be mined from (Water) Asteroids. Works great with MPDs (haven't got VASIMIR yet).

**Comment by arivaldh** [comment]
Single tank was missing HTP.
https://github.com/arivaldh/KSP-Interstellar-Extended/commit/07cd7bdbab4180dd49fbdc3affcc159b5382cc0a
Although question is whenever it also should have boiloff (currently it's missing)

**Comment by sswelm** [comment]
yes, boil off should be added as well
