### ISSUE TITLE
Electric charge / megajoules recharge rate doesnt scale properly with timewarp

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#107]
Theres a peculiar behaviour in interstellar - the size of megajoules / electric charge storage scales up with timewarp therefore timewarping does not help much with recharging those resources faster. 

![](https://i.imgur.com/IJe1eOQ.jpg)

![](https://i.imgur.com/zOB0C1S.jpg)

![](https://i.imgur.com/xZi4YBh.jpg)

Please tell me this isnt intentional ... 😄

**Comment by annikkexe** [comment]
I see this issue too.  I have a station on Minmus with Solar Panels and Batteries to generate electric charge, which is used by Science Modules.  On x1 speed, the batteries rapidly run dry at night.  On x100 speed they last all night.  The scaling for electric charge seems incorrect during timewarp.

My station is much simpler than the OP's and yet still has this issue.

![minmus station](https://user-images.githubusercontent.com/8266835/31401690-95d1b0e2-adeb-11e7-96ba-5f1057378a6e.png)

**Comment by sswelm** [comment]
This behaviour is intentional. It is to prevent power buffer underrun in which is when the amount of power consumed during a game tick (during high time warp) exceeds the total power buffer size.

**Comment by annikkexe** [comment]
Ah okay.  That seems like a bit...odd.  In my case that means a base that doesn't function properly at x1 speed, functions fine if I run at x10,000 speed.  Surely time warp should be transparent in terms of resources production/consumption?

The bug you describe with power buffers sounds interesting.  How come we scale the power consumption/production by greater than 1:1 proportional?  Is there anywhere I can read more about that issue please? :>

**Comment by annikkexe** [comment]
This seems 100% like a bug to me.  Please could you describe how can I revert to the original scalings for power during timewarp?  I would like to test the Power Buffer Underrun bug for myself. :>

**Comment by sswelm** [comment]
upcoming beta will adress this issue
