### ISSUE TITLE
IFS-Core lacks Localization folder

### ISSUE THREAD

**Issue by Real-Gecko** [sswelm/KSP-Interstellar-Extended#115]
As a result, mods that use only core will have wierd messages like this:
![screenshot0](https://user-images.githubusercontent.com/2231969/31439860-9918ec42-aeaf-11e7-9b39-aad41d2f701b.png)

**Comment by sswelm** [comment]
I see, I guess the localisation folder also have to be included. I will make it so

**Comment by sswelm** [comment]
Alright, I made the [pull ](https://github.com/KSP-CKAN/NetKAN/pull/5936/files)request to all localisation to IFS Core. Stange that no one else mentioned it earlier

**Comment by Real-Gecko** [comment]
PR was merged and everything is cool now, thanks :)
