### ISSUE TITLE
Candle Engine Graphics Glitch

### ISSUE THREAD

**Issue by alexJones2** [sswelm/KSP-Interstellar-Extended#120]
The Candle engine has been repeatedly and consistently causing a graphics glitch for me. Whenever the engine is staged/activated, the camera instantly goes black. The UI is still visible. Pressing escape brings the camera back but with most textures either black or see through.

I've tried this and it happens on both KSP version 1.3.0 and 1.3.1, with the relevant mod version for each. It happens when KSPIE is the only mod installed. It does not actually cause a crash, but I need to completely exit out and restart the game to fix the textures. I have put every combination of keywords on google I could think of but I can't find any related issues.

Any ideas?

Pictures:

At launch, before staging:
https://i.imgur.com/70U5aHC.png

As soon as I press space to stage:
https://i.imgur.com/HeWzuxF.png

Then if I immediately hit Escape:
https://i.imgur.com/hvN8RrD.png

After closing escape menu:
https://i.imgur.com/o6AaLk4.png

**Comment by darkhaze2009** [comment]
I have same problem.

**Comment by alexJones2** [comment]
Thanks, the new beta fixed this.
