### ISSUE TITLE
Timberwind has black plume texture

### ISSUE THREAD

**Issue by vdubikhin** [sswelm/KSP-Interstellar-Extended#132]
Timberwind engine has black plume:
https://preview.ibb.co/fdZgFw/screenshot17.png

Post on the forums:
https://forum.kerbalspaceprogram.com/index.php?/topic/155255-131-ksp-interstellar-extended-kspie-1161-20-10-2017-support-release-thread/&do=findComment&comment=3209719

**Comment by sswelm** [comment]
mmm, it looks we have lost some media files, I will add them back in

**Comment by vdubikhin** [comment]
Will you be able to fix this issue before the next major release? I can fix code, I can not fix missing/broken textures.

**Comment by sswelm** [comment]
Yes, I will handle this is I can

**Comment by arivaldh** [comment]
has this been solved? I can look into it if not.

**Comment by sswelm** [comment]
yes it is solved
