### ISSUE TITLE
Field Translation Not Working 

### ISSUE THREAD

**Issue by EthanWang706** [sswelm/KSP-Interstellar-Extended#134]
I tested in KSP v1.3.1.1896, all translation became blocks, it's normal if I open in textEdit, only not working in game

**Comment by EthanWang706** [comment]
@sswelm @Iso-Polaris

**Comment by EthanWang706** [comment]
Sorry, I just type in the wrong version, it's v1.3.1.1891
Can anybody check why?

**Comment by sswelm** [comment]
I will check if I can reproduce

**Comment by EthanWang706** [comment]
@sswelm OK, Thanks, I will try it again tonight, I hope it's working so we can publish this localization.

**Comment by EthanWang706** [comment]
Worked out fine when having a version higher than 1.16, but become block in older version for unknown reason @sswelm so should we delete this issue or try to fix the problem on older version?

**Comment by sswelm** [comment]
just close it for now
