### ISSUE TITLE
Compatibility Issues with Kerbal Konstructs

### ISSUE THREAD

**Issue by ShakenU** [sswelm/KSP-Interstellar-Extended#140]
Compatibility issues with Kerbal Konstructs, I am opening an issue with them as well. Fresh install of the game, no other mods installed. Crash happens right after main loading screen, just before you get to main menu. 

[buildID64.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/1464105/buildID64.txt)
[error.log](https://github.com/sswelm/KSP-Interstellar-Extended/files/1464101/error.log)
[output_log.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/1464102/output_log.txt)

**Comment by ShakenU** [comment]
Both mods were installed from fresh clones of their respective git repositories.

**Comment by sswelm** [comment]
Git repository is not guaranteed to function, only beta and full releases are

**Comment by ShakenU** [comment]
Fair enough, installing from a zip has no issues.
