### ISSUE TITLE
No power from reactors!

### ISSUE THREAD

**Issue by andy170886** [sswelm/KSP-Interstellar-Extended#142]
i put a reactor with a generator with some radiators on a vessel and no power is generated at all!

how is it supposed to work? there arent any instructions at all!

**Comment by EthanWang706** [comment]
First, this is not a place to ask questions like how to use reactors, this is a place to report issues of this mod.
Also, if you want to solve this problem, please give us a screenshot how your ship looks like or all KSPIE parts on the ship.

**Comment by andy170886** [comment]
So where do i go to ask questions on to ask how to use this mod? Plus it is an issue if the reacrors arent producing any power!

**Comment by EthanWang706** [comment]
Okay, could you send a screenshot or tell us what's on your spacecraft?

**Comment by EthanWang706** [comment]
OK sorry, I mean ALL parts, include the quantity, also please tell us what reactor, what generator and what radiator that you're using, simply tell us a reactor, a generator, and some radiator cannot solve any problem.

**Comment by arivaldh** [comment]
@sswelm I'd recommend the issue to be closed. No constructive response from the author of the issue.
