### ISSUE TITLE
Engine forces reactor to turn on even if it is turned off.

### ISSUE THREAD

**Issue by vdubikhin** [sswelm/KSP-Interstellar-Extended#150]
In a craft consisting of a thermal nozzle, am reactor, am tank and control pod engine will force turn the reactor, when it is activated. Is this working as designed? If so, is it possible(as in can I submit a patch) to change this behavior, so the engine respects reactor setting and does not turn it on accidentally?

**Comment by sswelm** [comment]
It is intended behavior a reactor is activated when the nozzle is activated. It is to make it easier for casual player to use KSPIE
