### ISSUE TITLE
REQUEST: File Removal

### ISSUE THREAD

**Issue by 7ranceaddic7** [sswelm/KSP-Interstellar-Extended#161]
As a matter of tidiness, can we remove the below file?  They, themselves state obsolete or empty or removed.

KSP_linux/GameData/WarpPlugin/Parts/Electrical/QuantumSingularityReactor2/Upgrades.cfg'.
KSP_linux/GameData/WarpPlugin/Parts/Microwave/BlanketRectennaReceiver/solarpanel-blanket-1.cfg'.
KSP_linux/GameData/WarpPlugin/Parts/Microwave/FELA/FELA-reflective_TR.cfg'.
KSP_linux/GameData/WarpPlugin/Patches/RadialDrillFix.cfg'.

**Comment by sswelm** [comment]
good point it is time to remove them
