### ISSUE TITLE
CDT7Setups.cfg ModuleManager error fix

### ISSUE THREAD

**Issue by milljm** [sswelm/KSP-Interstellar-Extended#162]
There appears to be an issue with a missing file:

https://github.com/sswelm/KSP-Interstellar-Extended/blob/a67b9037386210d9f34e29a7675148d1744d98dd/GameData/InterstellarFuelSwitch/PatchManager/CDT7Setups.cfg#L5

Previous ModuleManagers does not catch this error. But I admit I know very little about what actually causes an 'error'...

Regardless, I think the file which is currently located in
```pre
PatchManager/ActiveMMPatches/CDT7Setups.cfg
```
Belongs in:
```pre
PatchManager/PluginData/
```

That solves the 'error' message anyway.
PR incoming...

**Comment by milljm** [comment]
Well... This PR certainly solves the 'error' that crops up during load by the ModuleManager. But the parts in question no longer have fuels. Wooops.

Closing this issue. Its not the fix, and would make matters worse.

**Comment by sswelm** [comment]
I think we need to call in the cavalry and post the issue on the Module Manager forum and ask for advice
