### ISSUE TITLE
1.16.3 has broken Timberwind engine

### ISSUE THREAD

**Issue by cybergrind** [sswelm/KSP-Interstellar-Extended#164]
After 1.16.3 update Timberwind engine has stopped working with errors about a generator that isn't attached. 
Downgrade to 1.16.2 fixes issue

**Comment by sswelm** [comment]
ok, I will look into it

**Comment by arivaldh** [comment]
Has it been solved?

**Comment by sswelm** [comment]
Yes, I have fixed it, it will be rolled out next release
