### ISSUE TITLE
Antimatter Container as root part explodes when ship unloades

### ISSUE THREAD

**Issue by X4n01** [sswelm/KSP-Interstellar-Extended#176]
When ship with root Antimatter Container is reaching 2.5km away it gets unloaded. 
It shows the message from :         
```
void OnJustAboutToBeDestroyed()             
(...)
else
                doExplode("Antimatter container exploded for unknown reason");
```
than whole ship is than "collapsed"/unloaded and basically destroyed. 
When same ship has different root element it gets normally unloaded. 
Tested on same ship launched twice with different root element. 
Poor image of ship exploding when reaching 2.5km with some snapshot of logs: 
![bez tytulu](https://user-images.githubusercontent.com/35401105/35593755-13c7d828-0611-11e8-8be6-f406c502dcb1.jpg)

I guess that when unloading it sends signal and `OnJustAboutToBeDestroyed `catches it (wrongly) and later `ExplodeContainer()`; is called

**Comment by X4n01** [comment]
probably solution will be to add additional OR here: 
` if (!HighLogic.LoadedSceneIsFlight || antimatterResource.amount <= minimimAnimatterAmount || !FlightGlobals.VesselsLoaded.Contains(this.vessel)) return;
`

**Comment by sswelm** [comment]
what to chance?

The problem is to distinguish between being destroyed by an event (collision, overheating or stress) or when unloading. In both cases the OnJustAboutToBeDestroyed is called

**Comment by sswelm** [comment]
I think I have fixed it in 
https://github.com/sswelm/KSP-Interstellar-Extended/commit/339c5f441ca70d0a84a448d1bd2cec15ec4fa9a5at least in test it explodes when it should and doesn't when it shouldn't

**Comment by X4n01** [comment]
Ok Thanks
I will check it.
