### ISSUE TITLE
Wrong Unit in Uranium Tetraflouride Ammolysis Reaction

### ISSUE THREAD

**Issue by EthanWang706** [sswelm/KSP-Interstellar-Extended#177]
29kg of UF4+ 8kg of Ammonia =300+ton of UN
currently no screenshots, I will try to provide 1 later

**Comment by EthanWang706** [comment]
@sswelm

**Comment by lennywangnerd** [comment]
Yo

**Comment by arivaldh** [comment]
I'll add it to my backlog.

**Comment by arivaldh** [comment]
I have fixed the issue:
https://github.com/arivaldh/KSP-Interstellar-Extended/commit/d3b7bb3bdb4fa0cae8cb7587b13c05626b7958a4
