### ISSUE TITLE
ETT.cfg error

### ISSUE THREAD

**Issue by 7ranceaddic7** [sswelm/KSP-Interstellar-Extended#185]
ln11&12 in KSP-Interstellar-Extended/GameData/WarpPlugin/Patches/ETT.cfg need to be combined.

Is:
ln11    @PART[KSPIE-VASIMR
ln12    ]:NEEDS[ETT]:FINAL

Shoud be:
@PART[KSPIE-VASIMR]:NEEDS[ETT]:FINAL

**Comment by sswelm** [comment]
done
