### ISSUE TITLE
Fuel Switch:  Fuel Tank Collision/Attachment Issues

### ISSUE THREAD

**Issue by lupinia** [sswelm/KSP-Interstellar-Extended#187]
Hi!  Interstellar Extended is wonderful, but I've been running into a brick wall in my ship designs that doesn't appear to have a solution:  The fuel tanks in Interstellar Fuel Switch simply will not stay attached to the ship.  If I put them inline in a stack between other components, they randomly detach and split the ship in half, even with struts.  If I attach them radially, they fall off as if they were never attached at all, usually while sitting on the launch pad.  And if I attach them inline to a tank that's attached radially, they detach mid-flight in a way that causes an explosion.  

I'd be here all day if I listed all the specific instances where I've encountered this, but the one that prompted me to submit an issue is a new design for a warp-capable ship I'm working on.  The main fuel source for the sub-light engine is Lithium Hydride, which can only be stored in the IFS cargo containers, and I cannot find a single configuration that doesn't result in a collision and explosion entering/exiting warp (on the rare occasions when it doesn't disassemble mid-launch).  

I can provide whatever further information is needed to properly diagnose this.  Thanks!

EDIT:  This isn't limited to just the cargo containers.  A brief list of tank configurations I can remember; every single one of them had this issue in every configuration:  

- Cargo Container (varying sizes) with Lithium, Lithium6, LithiumDeuteride, or LithiumHydride.
- Cryogenic Dual Tank (CDT2505) with LFO, HydroLOX, or Liquid Hydrogen.  
- Cryogenic Tank (literally every size) with Liquid Deuterium, Liquid Helium, Hydrazine, Liquid Hydrogen, or Liquid Xenon.
- Pressurized Gas Tank (PGT2501) with Argon Gas, Hydrogen, or Xenon Gas.

The only ones I haven't tried are the Radioactive Fuel Containers, because I haven't yet built a ship powered by anything that requires those.

**Comment by sswelm** [comment]
Possible reason is you are stressing the parts too much. A possible solution would be to increase their breaking force . You can achieve this by opening a parts fill and add or change the breaking force to ridiculous number like
`
	breakingForce = 10000
	breakingTorque = 10000
`
alternatively use a mod like KerbalJointReinforcement which will do this automaticly
