### ISSUE TITLE
B9PartSwitch should be ModuleB9PartSwitch

### ISSUE THREAD

**Issue by blowfishpro** [sswelm/KSP-Interstellar-Extended#192]
https://github.com/sswelm/KSP-Interstellar-Extended/blob/b0a3f80fa9be7dbdaef6eb017ae941b7241eab77/GameData/InterstellarFuelSwitch/PatchManager/ActiveMMPatches/IntegrationLiquidFuel.cfg#L1

https://github.com/sswelm/KSP-Interstellar-Extended/blob/f9e08ded93f3f0e114c9ae3cd5280da5b965fb5f/GameData/InterstellarFuelSwitch/PatchManager/ActiveMMPatches/IntegrationLiquidFuelOxidizer.cfg#L1

https://github.com/sswelm/KSP-Interstellar-Extended/blob/f9e08ded93f3f0e114c9ae3cd5280da5b965fb5f/GameData/InterstellarFuelSwitch/PatchManager/ActiveMMPatches/IntegrationLiquidFuel.cfg#L1

https://github.com/sswelm/KSP-Interstellar-Extended/blob/f9e08ded93f3f0e114c9ae3cd5280da5b965fb5f/GameData/InterstellarFuelSwitch/PatchManager/ActiveMMPatches/IntegrationLiquidFuelOxidizer.cfg#L1

**Comment by sswelm** [comment]
oh, is it renamed now?

**Comment by blowfishpro** [comment]
It was always `ModuleB9PartSwitch`.  I was just following the convention of all modules starting with `Module`, which makes it different from the name for the mod

**Comment by sswelm** [comment]
Should be fixed in latest release
