### ISSUE TITLE
Problem with joints. 

### ISSUE THREAD

**Issue by Meperidine** [sswelm/KSP-Interstellar-Extended#194]
Hey this is one of my top 5 mods in all of KSP, was installing for the latest release and realized that KerbalJointReinforcement isn't working like past installs. It is acting like its not even installed, was wondering if this was brought to you guys attention. Thanks and love the mods...

**Comment by sswelm** [comment]
thank for bringing this to my attention. Most likely the mod disables itself after detecting another version than 1.3.1.   I suggest you head over to KerbalJointReinforcement and look for an updated version of hack to make it functional. Technically KerbalJointReinforcement  is not required to play KSPIE but it is recommended, especially if you want to make realistic looking planetary/installer vessels

**Comment by Meperidine** [comment]
I actually did a clean install and dL of all mods I wanted that are available! Will try wiping and just installing KJR and see if I’m still having this problem!
