### ISSUE TITLE
VAB Thermal Helper gives bogus results

### ISSUE THREAD

**Issue by arivaldh** [sswelm/KSP-Interstellar-Extended#196]
There's quite a difference between calculation results of VAB Thermal Helper and that of a vessel once it's launched.
I'll try to implement a simulation in the Helper that will calculate 100- steps of simulation per frame/update in order to give the player better results.
Last forum reference:
https://forum.kerbalspaceprogram.com/index.php?/topic/172026-131-14-ksp-interstellar-1174-support-thread/&do=findComment&comment=3315807
Although I positive that there were many other older posts about that issue.

**Comment by sswelm** [comment]
Sounds interesting. But wouldn't it be easier to tweak the existing projected thermal load. From my knowledge it main shortcomming was that is didn't take into account direct conversion which have a fixed conversion rate (based on tech level and fuel mode) therefore should be fairly simple to predicts it effect on wasteheat

**Comment by arivaldh** [comment]
I believe that's not the case.
Simplest calculations (1 molten salt reactor + 8 radiators), give incorrect results.

**Comment by chris9871** [comment]
They also give different results if you have a solid fuel electric fission reactor added to an existing system.  E.g. Add a pebble bed (4.8GW heat production), 4 VF-600 (4.25GW heat dissipation).  Then add the SFEFR and it reports 4.8GW heat production, but 188 MW heat dissipation.
