### ISSUE TITLE
NearFutureElectrical WasteHeat management + Generator Efficiency

### ISSUE THREAD

**Issue by arivaldh** [sswelm/KSP-Interstellar-Extended#198]
WasteHeat resource is currently missing from NearFutureElectrical Fission Generator adapter. Generator Efficiency is also always at 100% effectivness (although I don't know if it should be changed).

Submitting issue so that it will be known to the community and remembered by developers.

**Comment by sswelm** [comment]
For now that's alright. From my understand these reactor use thermal electric effect generator. The advantage is that they are quite reliable and have a fixed efficiency. The disadvantage is they have very low efficiency.

**Comment by arivaldh** [comment]
Ok. So I assume that nothing else needs/can be done. NFE fission reactor generates heat (using stock heat), so there's even no reason to make it to store/transfer waste heat.
If so, this issue can be closed.

**Comment by sswelm** [comment]
Well no because if you mix the 2, the radiator will do double the work. What we could do is assume the NFE reactors have a fixed efficiency of 10% and therefore inject 10 times the amount energy in wasteheat.

**Comment by arivaldh** [comment]
According to sources, efficiency in thermal electric generators (in the future) can achieve more than the current 5-8%. So 10% is a positive guess.
Ok. But I doubt we would be able to remove Stock heat. But I believe that some stock heat is no problem. What is the unit of WasteHeat?

**Comment by sswelm** [comment]
The same as ThermalHeat in Megajoules. Meaning a NFE Reactor producing 1 MG ElectricCharge should also produce 9 units of Wasteheat.

**Comment by arivaldh** [comment]
Once
https://github.com/arivaldh/KSP-Interstellar-Extended/commit/a0defb83a467a547b17e5db3f2e076d1755feefd
will be merged, this issue can be closed, since the commit added WasteHeat resource to NFE Fission Generators and WasteHeat is properly generated by it.
