### ISSUE TITLE
Strange behavior of Radiators

### ISSUE THREAD

**Issue by arivaldh** [sswelm/KSP-Interstellar-Extended#203]
When Pivot is not Enabled there are strange things that Radiators can do.

They can use Pivot even though it's disabled
https://imgur.com/9MXCp1x
https://imgur.com/kiBbXIV

They can be "Retracted" but for some reason "Power Radiated" is positive.
https://imgur.com/GqwaKZf

Few releases ago they wouldn't change state from "Extending" to "Extended", when Pivot was disabled, but I don't seem to be able to reproduce it any longer.

**Comment by arivaldh** [comment]
This can be so since I'm still on 1.3.1 building dll from recent master. I'll try to update KSP to 1.4.1 and report back. Previously I have had the issue in the last paragraph. I'll update KSP.

**Comment by arivaldh** [comment]
Still present in 1.4.1 using 1.18.4.

**Comment by sswelm** [comment]
they are not cooling at all, or not enough. Notice cooling capacity depends on unlocked  thermal maintenance technology.

**Comment by gbcs** [comment]
Automated functionality requires pivot to be enabled. To test this, launch a craft with a radiator set to auto disabled, pivot disabled and radiator retracted. Click automated; radiators will extend, but not cool the ship until pivot is enabled (you'll see the percentage go from idle to some number when enabling pivot.)

Action groups don't work right for radiators either. Set the two toggle functions to separate action groups and find a combo to make your radiators start/stop;  doesn't seem deterministic, might be related to pivot.

**Comment by arivaldh** [comment]
I have raised this issue since Automation should *not* require a pivot to be enabled.
