### ISSUE TITLE
Retracted Microwave Power Receivers still on

### ISSUE THREAD

**Issue by arivaldh** [sswelm/KSP-Interstellar-Extended#205]
When using Microwave Power Receivers they're still on even though "Retract Panel" button was used.

https://imgur.com/T27xieL

It's not off, since WasteHeat buffer is on, Enabled = true, Produces Power != disabled, etc.

**Comment by sswelm** [comment]
It appears several animation got broke after KSP 1.4.1. I was atleast able to prevent them from making a part from starting all together but their animation still need to be repaired somehow

**Comment by arivaldh** [comment]
Ohh... right... this can be so since I'm still on 1.3.1 building dll from recent master. I'll try to update KSP to 1.4.1 and report back.

**Comment by arivaldh** [comment]
Still present on 1.4.1 using 1.18.4

**Comment by sswelm** [comment]
There appears an initialisation issue where the controller thinks the animation is active while it isn't.

**Comment by liyingcake** [comment]
It can be avoided by manual switching "Beam power" to "solar power" to stop Receivers power.

**Comment by liyingcake** [comment]
by the way, Radiator has a similar problem like that.
