### ISSUE TITLE
Graphite Radiator Skin Wrapper heat dissipation

### ISSUE THREAD

**Issue by chris9871** [sswelm/KSP-Interstellar-Extended#221]
As calculated by the Interstellar Thermal Mechanics Helper, the 'Skin Wrapper' variants of the graphite radiators give notably higher performance per weight than the other radiators in spite of the fact that the description says "They sacrifice some cooling capacity for [fitting smoothly]."

KSPIE 1.19.2

**Comment by sswelm** [comment]
Graphene maximum temperature is limited in atmosphere and don't have any convection bonusses

**Comment by chris9871** [comment]
That makes sense, but isn't that a different issue than the performance description seemingly being inaccurate?

**Comment by sswelm** [comment]
True. Perhaps you can think of a better description? Making up description is not my strong point.

**Comment by chris9871** [comment]
Sure, I'll think about it.

**Comment by chris9871** [comment]
This issue may actually be that the thermal helper is giving a misleading result and that the skin wrappers show on the thermal helper as being super efficient per weight.  They are notably better on the thermal helper per weight than just about every other radiator.

**Comment by sswelm** [comment]
Skin rappers were designed to be the lightest in the game, because they don't need any support structure.

**Comment by chris9871** [comment]
Ah, that makes sense, thanks!
