### ISSUE TITLE
Thermal Generators Fail When Undocking

### ISSUE THREAD

**Issue by chris9871** [sswelm/KSP-Interstellar-Extended#223]
Steps:
1. Create a station with a (large) thermal generator.
2. Create a ship with a (small) thermal generator or solid fuel electric fission reaction.
3. Dock the ship.
4. Reload the station/ship (switch to tracking station and back).
5. Undock the ship and move out of physics range of the station.
Result: The ship does not have power generation until it is reloaded.

KSPIE 1.19.2

**Comment by sswelm** [comment]
should be fixed now.

**Comment by chris9871** [comment]
Verified!  Awesome!
