### ISSUE TITLE
Radial Cryogenic Liquid Fuel Tank X11 catastrophic explosion

### ISSUE THREAD

**Issue by chris9871** [sswelm/KSP-Interstellar-Extended#225]
Craft:
probe core, power, central fuel tank (e.g. cdt2505) ready for LH2 and empty (may need to upscale to have enough space).
2 (or more) symmetry, add X11 to the central fuel tank, and upscale to 1.5x (doesn't happen on 1x).

Launch, select all 3 (or more) fuel tanks and move all the hydrogen to the central fuel tank, emptying the X11s.  When the X11s reach a certain level, the craft is obliterated and sometimes parts will achieve relativistic speeds.

KSPIE 1.19.2

**Comment by Khalkion** [comment]
I think this happens because X11 have negative mass on upscale. This can and will create WEIRD things.
Changing tweakscale type = stack_interstellar_275 to type = stack fixes the issue.

**Comment by sswelm** [comment]
Problem should already be fixed
