### ISSUE TITLE
Thermal Turbojet flame-out when using non-atmospheric fuel

### ISSUE THREAD

**Issue by chris9871** [sswelm/KSP-Interstellar-Extended#226]
When in the upper atmosphere (Kerbin 50k+ usually), where the Thermal Turbojet would flame-out on ATM, sometimes other fuels (LH2 and LF) will also flame-out.  Sometimes save/reload will cause the flame-out to end.  Almost always (but not always), leaving the atmosphere will end the flame-out condition.

KSPIE 1.19.2

**Comment by pszabop** [comment]
Same issue here.  Thermal turbojet is basically unusable for SSTO because of this.
