### ISSUE TITLE
Closed Cycle Gas Core Engine Warp/NonWarp ISP inconsistent

### ISSUE THREAD

**Issue by chris9871** [sswelm/KSP-Interstellar-Extended#227]
With a 'Closed Cycle Gas Core Engine' on a craft, monitoring with MechJeb, I noticed that the actual DeltaV applied to the ship per fuel was different in and out of warp.  The factor may be x2, however I didn't verify this beyond a rough eyeballing of the numbers.

E.g. Applying a 8000 delta-v maneuver: Without warp (or using physics warp) took 16,000 delta-v of fuel.  In warp took ~8000 delta-v of fuel.

The ship I tested with was a fairly light ship: Engine, 7x cdt2505, graphite radiators, probe core, reaction wheel, battery, antenna, and some science.  Total weight 45t.

KSPIE 1.19.2

**Comment by chris9871** [comment]
I notice that the CANDLE Traveling Wave Reactor Engine also uses a different amount of fuel than the ISP indicates, perhaps 1.6x.  The ISP changes as the thrust changes, but not by anywhere near this factor.

**Comment by sswelm** [comment]
when travelling at timewarp it applies some time dilation effects, but it shouldn't start to become significant unless going faster than reaching 0.01c.

**Comment by sswelm** [comment]
Well it uses stock engine for normal time propulsion. Seems more likely mechjeb calculation is wrong.

**Comment by chris9871** [comment]
It's possible mechjeb is getting it wrong.  However the warp result is correct in mechjeb, and the non-warp result uses a lot more fuel, so something is still wrong outside mechjeb.

**Comment by chris9871** [comment]
The same thing seems to apply to the Open Cycle Gas Core Rocket.  When executing a node, it uses twice as much fuel outside warp as inside warp.

**Comment by sswelm** [comment]
what about regular stock engines, does MechJeb register their fuel consumption correctly?

**Comment by chris9871** [comment]
It does seem to.  Also many of the kspie engines seem to work compatibly with Mechjeb: VASIMR (in and out of warp), Plasma Nossle, Thermal Turbojet, Attila  (in and out of warp), Magneto  (in and out of warp).

**Comment by chris9871** [comment]
Noted by emiliofloris @ https://forum.kerbalspaceprogram.com/index.php?/topic/172026-131144-ksp-interstellar-extended-1193-support-thread/&do=findComment&comment=3410750 this may be caused by a discrepancy between fuel flow on the engine and out of the tanks.

**Comment by chris9871** [comment]
Further info collected by Khalkion: https://forum.kerbalspaceprogram.com/index.php?/topic/172026-131144-ksp-interstellar-extended-1193-support-thread/&do=findComment&comment=3414997

**Comment by sswelm** [comment]
Issue should be fix now
