### ISSUE TITLE
Models for Microchannel Radiators missing in distributable

### ISSUE THREAD

**Issue by davidson16807** [sswelm/KSP-Interstellar-Extended#234]
Tried upgrading to KSP 1.4.5 with KSPIE 1.19.4. A bunch of old craft wouldn't load up and KSP.log presented with errors similar to the following:

 
> [LOG 20:08:04.209] PartLoader: Compiling Part 'WarpPlugin/Parts/Radiators/Microchannel/radiator-microchannel-1/KspiMicrochannelRadiator1'
> [ERR 20:08:04.209] PartCompiler: Cannot clone model 'HeatControl/Parts/Radiators/radiator-microchannel/radiator-microchannel-1' as model does not exist
> 
> [ERR 20:08:04.209] PartCompiler: Model was not compiled correctly
> 
> [ERR 20:08:04.209] PartCompiler: Cannot compile model
> 
> [ERR 20:08:04.209] PartCompiler: Cannot compile part

the .mu and .dds files are indeed  missing: the "HeatControl" folder does not exist. Copying the files over from my older copy of KSP 1.2 resolved the issue.

**Comment by sswelm** [comment]
Due to license constraints, you need to download the mod HeatControl seperately to make use of KSPIE revisioned microchannel radiator

**Comment by davidson16807** [comment]
Alright, thanks. If this is well documented then let's call me dumb and close this issue.
