### ISSUE TITLE
Radially Attached VASIMR Engine (VASIMR2) Texture Missing

### ISSUE THREAD

**Issue by chaoseclipse01** [sswelm/KSP-Interstellar-Extended#236]
It would seem the Radially Attached VASIMR Engine (VASIMR2) is failing to render the texture onto the engine ingame, as it shows up as a completely black object. I converted the .dds texture file for the VASIMR2 Engine Part into a .png and found it's only a small black square, so the texture file is missing. I couldn't find anyone talking about this issue in either the development thread nor here so I decided to bring it up here.

Here's the original .dds file (In .zip) from the 1.19.4 release of the file as well as the converted .png file I got from the .dds file:

[model001.zip](https://github.com/sswelm/KSP-Interstellar-Extended/files/2292546/model001.zip)
![model001](https://user-images.githubusercontent.com/27385078/44191220-e8e8d100-a0ef-11e8-8942-75d563d31778.png)

**Comment by sswelm** [comment]
mmm. I guess something went wrong in the dds conversion step, this should be easily fixable

**Comment by sswelm** [comment]
a new model with texture are uploaded
