### ISSUE TITLE
Haber Process Hydrogen usage

### ISSUE THREAD

**Issue by samelias** [sswelm/KSP-Interstellar-Extended#239]
The Haber Process consumes Nitrogen and produces Ammonia at full rate as long as there is any steady supply of Hydrogen(from electrolysis or atmo processor), no matter how small. 
[Imgur](https://i.imgur.com/NQbu6un.jpg)

Also, if Hydrogen runs out and the steady supply is interrupted, Haber Process continues eating Nitrogen and power but produces nothing.

**Comment by sswelm** [comment]
It should be fixed next release, please verify that it does

**Comment by samelias** [comment]
Tested on 1.20 release. The process refuses to work with "insufficient storage", even though I have room for Ammonia in both liquid and gas form.
[Imgur](https://i.imgur.com/uLPy2qB.jpg)

Though strangely the ISRU process window correctly identifies spare Ammonia capacity.

**Comment by samelias** [comment]
Confirmed working on 1.20.17. Thanks
