### ISSUE TITLE
WARP PLUGIN TRANSLATION es-es?

### ISSUE THREAD

**Issue by SergiRuizZarzuelo** [sswelm/KSP-Interstellar-Extended#241]
Hi:
Does this plugin needs trnaslation into spanish??

**Comment by sswelm** [comment]
Yes, the part descriptions and titles need translations.

**Comment by SergiRuizZarzuelo** [comment]
OK. Work in progress……..

**Comment by sswelm** [comment]
Good work. Notice that not everything is properly localized yet. I will notify you if there are significant changes and additions.

**Comment by SergiRuizZarzuelo** [comment]
Ok.
I'll wait news….
________________________________
De: sswelm <notifications@github.com>
Enviado: viernes, 12 de octubre de 2018 14:42
Para: sswelm/KSP-Interstellar-Extended
Cc: SergiRuizZarzuelo; Author
Asunto: Re: [sswelm/KSP-Interstellar-Extended] WARP PLUGIN TRANSLATION es-es? (#241)


Good work. Notice that not everything is properly localized yet. I will notify you if there are significant changes and additions.
