### ISSUE TITLE
Fuel type bug when using symmetry.

### ISSUE THREAD

**Issue by ConCon2** [sswelm/KSP-Interstellar-Extended#242]
Ok usually when I find bugs in mods I go scientific experiments detail picking mode to get as much info on it in a few hours and rap all up best I can for the authors, but your mod is still so big and convoluted to me (and I love it) I don't know where I would start so here is just the series of of events that are taking place here.

After experimenting with the ATTILA to see how the thrust and efficiency rating of the fuel options work and interact with each other then realizing xenon just has the best of both and is earth shatteringly expensive I make this to move the box on the bottom throw space. The bug applies to the two xenon containers on the sides which I have the windows for open. 
![image](https://user-images.githubusercontent.com/10994888/46252756-e8539200-c432-11e8-9dc1-fb8c641a93c2.png)

I launch it to recheck the engine performance and notice one engine is using xenon the other hydrazine trying to figure out where its even getting hydrazine I find the right xenon container became hydrazine.
![image](https://user-images.githubusercontent.com/10994888/46252817-d58d8d00-c433-11e8-961f-cd7a704c0315.png)

I revert the game back to the VAB to check the contaners and have this in there windows.
![image](https://user-images.githubusercontent.com/10994888/46252842-37e68d80-c434-11e8-9b04-665b8271ccbb.png)
The right one still says xenon and stuff but look at the fuel selector.

I try moving the slider back but the fuel only changes every other click of the arrows. But then the left ones slider has an error message.
![image](https://user-images.githubusercontent.com/10994888/46252880-dffc5680-c434-11e8-934e-a12a48353274.png)

I move the left one by clicking were xenon is on the slider and now both tanks say hydrazine.
![image](https://user-images.githubusercontent.com/10994888/46252898-218d0180-c435-11e8-85fd-79768c58a624.png)

Now looking at this a bit more while the fuel only changes every other space the left slider still has the right amount of spaces for the number of fuels but the right one has double so.... um.... let me make up a drawing.
![ksp graph](https://user-images.githubusercontent.com/10994888/46259552-7fa2fe80-c4a0-11e8-9952-850ca5aad871.jpg)
Like my google drawing skills.

If you are wondering about the hitpoints and armor I'm running BDarmory to clear derby not worth collecting. I think this is the longest bug report I have ever given.

**Comment by ConCon2** [comment]
I think I found more info. When the craft is first loaded the right tank switches to the fuel type corresponding the my left tank drawing (Xe->N2H2, He->D2, H2O->H2O2, ext) Then if you revert the craft the fuel slider for the right tank corresponds the same way. Then if you use a symmetry greater then two (3,4,6,8) then the original part is the "left tank" and the duplicates are the "right tank"

**Comment by sswelm** [comment]
Bug is fixed in 3.6.12
