### ISSUE TITLE
KSP-IE "somehow" triggers issues in Kerbalism with RemoteTech

### ISSUE THREAD

**Issue by Gordon-Dry** [sswelm/KSP-Interstellar-Extended#243]
See here:
https://github.com/steamp0rt/Kerbalism/issues/221

It's weird, but at the end the removal of these mod folders solved the issue:
InterstellarHybridRocketry\
WarpPlugin\
TweakScale\

I tried it first by removing these folders, but that didn't work:
PhotonSail\
RealHeat\
SolarSailNavigator\

**Comment by leomike** [comment]
Can you try:
* Kerbalism and TweakScale only
* Kerbalism and Interstellar Extended only

_Including dependencies in both cases for installed mods_

**Comment by Gordon-Dry** [comment]
I would have to reproduce that particular issue, which was a vessel in orbit had no more EC as resource in the persistent file after I added  KSP-IE - which made Kerbalism throw exceptions.
After removing KSP-IE and TwealScale, the vessel still had no EC in the persistence file, but Kerbalism no more threw exceptions and after loading that vessel in flight mode it was "repaired", so afterwards it also had EC  as a resource in the persistent file.
See https://github.com/steamp0rt/Kerbalism/issues/221#issuecomment-427864043

**Comment by Gordon-Dry** [comment]
This comment and the following could™ describe the reason:
https://github.com/steamp0rt/Kerbalism/issues/221#issuecomment-427927546
