### ISSUE TITLE
Thermal Ramjet Nozzle and Thermal Turbojet Fuel Change? 

### ISSUE THREAD

**Issue by nopenopenope** [sswelm/KSP-Interstellar-Extended#246]
I noticed that the both Engines dont support Liquid Fuel as fuel anymore. This broke some of my vehicles. 

Has this happened due to the recent splitup of those parts, config wise? I've seen some commits regarding those Engines.

**Comment by sswelm** [comment]
existing vehicles should be unaffected. Exactly which engine, reactor + nozzle were you using?

**Comment by nopenopenope** [comment]
Well, its been saved vehicles... Not existing ones - sorry for not making that clear in the first place. 

So based on your answer I can give the answer to myself, it was intended and what I did also wrong here was to uninstall other mods because I cleaned up my KSP. 

Any way to get the old ones in the game? I've seen some nodes in the configs for that, I'd just create my own branch over those files to keep them in place properly, but I have no idea how to make it possible KSP-wise. Could you assist me with that?

**Comment by sswelm** [comment]
Well notice that next release I will relay the requirements somewhat. The type of propellant is mainly determined by the reactor, not the engine. For example the positron antimatter reactor is controlled in WarpPlugin\Parts\Electrical\ThermalAntimatterReactor\ThermalAntimatterReactor2.cfg 
It has 2 proprtiwa called supportedPropellantAtoms and supportedPropellantTypes, when both set  to 511, everything will be unlocked. There might also be a setting called minCoolingFactor which when set to 2 will block non cryo propellants

**Comment by nopenopenope** [comment]
I was using the Dusty Plasma Fission Reactor. I've checked several reactors now and none seem to enable Liquid Fuel as option to select as propellant. Am I missing something?
