### ISSUE TITLE
Ground based microwave receiver unable to link with orbiting transmitter

### ISSUE THREAD

**Issue by NEIN-NEIN-NEIN** [sswelm/KSP-Interstellar-Extended#247]
The orbiting station is the power generator, the ground based platform is the intended recipient, I cycled between all available microwave bands on the cyclotron including X-band, and Ka-band but the two won't connect.

![screenshot0](https://user-images.githubusercontent.com/44105495/46899828-7bd28d00-ce4d-11e8-8656-0fb87246cae0.png)
![screenshot1](https://user-images.githubusercontent.com/44105495/46899829-7c6b2380-ce4d-11e8-801d-bc0bca8d43d6.png)
![screenshot2](https://user-images.githubusercontent.com/44105495/46899830-7c6b2380-ce4d-11e8-938a-0431f88f804a.png)

**Comment by NEIN-NEIN-NEIN** [comment]
In the second screenshot on the map view the cluster of craft on the mun visible is the location of the ground station. The ground station is situated at the base of a small crater, the walls do not occlude LOS with the orbiting station as it can clearly be seen flying overhead when light reflects off the dish.

**Comment by sswelm** [comment]
Iin KSPIE 1.20.6 I have made some alteration in the line of sight procedure to allivate the problem.Please let me know if it makes any difference.
