### ISSUE TITLE
Latest version says I haven't unlocked Vista Fusion Engine

### ISSUE THREAD

**Issue by psychonaut25** [sswelm/KSP-Interstellar-Extended#252]
I'm on KSP 1.3.1, I've unlocked the Vista Fusion Engine in the tech tree quite a long time ago, and I've been using it on several different crafts.  When I updated to KSPIE v1.20.13.0, a bunch of the crafts that I have saved (that I've already used a lot) say that they can't be launched because the Vista Fusion Engine is not unlocked.

**Comment by sswelm** [comment]
Because of high performance, the Vista Engine tech requirement have been significantly increased. You simply have to unlock the tech to make use of it again I'm afraid

**Comment by psychonaut25** [comment]
I have to admit, I was pretty drunk when I tried it, but as I recall I actually tried that and it still wouldn't work.  I have a lot of spare science laying around not being used, so I just went to the tech tree, and found it again, and unlocked it.  Also, the Vista Fusion Engines which I already had it orbit wouldn't produce a plume (they just kinda glowed blue) and didn't make any noise, but they did produce thrust.

I've reverted back to an older version of KSPIE, but when I get a chance to do more (sober) tests on the 1.20.13.0 I'll get back to you, most likely some time tomorrow.

**Comment by psychonaut25** [comment]
Ah, I think I've found the problem.

I still have the Vista engine in my parts list in the VAB.  These old ships are saved with the "old" Vista engine.  If I open each individual craft and replace their existing engines with a new one from the parts list, then they become unlocked.  This is going to require some tedious work, but I think it solves the problem.

I wonder if this will also solve the plume issue.  I will have to perform some tests.

**Comment by psychonaut25** [comment]
Ok, I've replaced every Vista Fusion Engine on every craft that uses it with the new version, and they're all unlocked.  However, I launched one of these crafts, and I'm still not getting a plume, nor any audio, from the Vista while it's operating and producing thrust.  It's the only engine I have which is having this issue.  I've tried uninstalling RealPlume and the issue did not go away.  I reinstalled RealPlume and the problem still hasn't gone away.  Should I open a separate issue and close this one?

**Comment by sswelm** [comment]
the plume issue with RealPlume  can be fixed by slightly fixing the realplume module manager script file by changing vista into vista3

**Comment by sswelm** [comment]
WarpPlugin\RealPlume\Vista.cfg

**Comment by psychonaut25** [comment]
@PART[vista3]:NEEDS[RealPlume,SmokeScreen] //D-T Vista ...?

That didn't seem to work

**Comment by psychonaut25** [comment]
Or did you mean change Vista.cfg to Vista3.cfg
