### ISSUE TITLE
KSPI Fuel Switch Mk. 4 Plane Parts

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [sswelm/KSP-Interstellar-Extended#253]
IFS is apparently not compatible with Mk. IV Plane System tanks.

**Comment by sswelm** [comment]
how so?

**Comment by bHXDgiuMa5yLHyC8** [comment]
I only have the option of filling tanks like the Mk. 4 Medium Fuselage with some combination of Liquid Fuel/Oxidizer/Monopropellant. Tested using IFS 3.6.16 and MkIVSystem 3.0.2. in KSP 1.5.1. Sorry for the undescriptive ticket, I just wanted to note this before I went to bed and forgot.

**Comment by sswelm** [comment]
Well IFS takes a back seat whenever a part already has some fuel switching configured. It only adds itself when it only contains stock resources.
