### ISSUE TITLE
No plume or sound from Vista Fusion Engine

### ISSUE THREAD

**Issue by psychonaut25** [sswelm/KSP-Interstellar-Extended#254]
The Vista Fusion Engine operates normally, and produces normal amounts of thrust, but while it's operating and producing thrust it has no plume and no audio.  There is somewhat of a blue glow coming out of the engine (or rather, being reflected from the nonexistent plume onto it), but that's it.

I can provide a list of my mods if necessary.  I do have RealPlume.  I tried uninstalling it and testing the engine again, and had the same result.  I then reinstalled RealPlume and tested it again, same result.

The Vista Fusion Engine is the only engine I'm having this issue with, so I think I've basically ruled out RealPlume as the issue.

**Comment by psychonaut25** [comment]
Still having this issue even after updating Interstellar Extended

**Comment by psychonaut25** [comment]
Updated to the latest version of Interstellar Extended, and the issue persists but has changed a bit.  There is now rather quiet audio coming from the Vista Fusion Engine, but the plume is just a three purple spheres vectoring out of the back of the engine that get smaller and dimmer as they go on.

I should have mentioned, I'm running KSP v1.3.1 on Windows 7 Professional x64.

**Comment by sswelm** [comment]
should be fixed now
