### ISSUE TITLE
Thermal Turbojet not working with antimatter 

### ISSUE THREAD

**Issue by Joeppie** [sswelm/KSP-Interstellar-Extended#256]
I am having trouble getting my thermal turbojet to function in Interstellar with antimatter reactors in KSP 1.5.1,  KSP interstellar, 1.20.15.2, in sandbox mode.

What I have observed is:

* it works for two fission reactors.
    * It does not work for the beam core antimatter reactor, specifically:
     * the reactor is powered. (has hydrogen and antimatter)
     * the reactor sees the radiator.
     * the reactor quickly overheats, and, last but not least:
         * the reactor tries to produce heat for the turbojet after overheating when I put its throttle to max, but the turbojet produces no thrust.

I've had this working in the past, using KSP 1.1, 1.2 and even I think 1.4 in the past, but it doesn't seem to work anymore. It's been over a year since I last played KSPi, but I am certain I had a setup like this working in the past.

**Comment by sswelm** [comment]
Beam Core Antimatter Reactor will not function with thermal turbojet, its simply too powerfull and would evaporate it in an instant. Instead you the positron antimatter reactor

**Comment by Joeppie** [comment]
> Beam Core Antimatter Reactor will no longer function with thermal turbojet, its simply too powerfull and would evaporate it in an instant. Instead you the positron antimatter reactor, which is mend for this task

Okay but how is one supposed to find this out? I spent over an hour working with antimatter power before giving up. Not having a clue as to why it wasn't working, as pointed out, I see inconsistent behavior: the reactor definitely responds to throttle action on the thermal turbojet.

There really should be a message to the user that this will not work, otherwise this is extremely confusing and disappointing.
