### ISSUE TITLE
Seismic Accelerometer will not record impact data

### ISSUE THREAD

**Issue by just-another-trash-account** [sswelm/KSP-Interstellar-Extended#258]
Seismic Accelerometer will not record impact data as least in KSPIE 1.20.5 and KSPIE 1.20.16

**Comment by sswelm** [comment]
The Seismic Accelerometer is kind or replaced by other mods which do something similar but better. Its not really part of KSPIE core functionality, which is power generation, power distribution, propulsion and ISRU, so I will remove it from KSPIE for now.
