### ISSUE TITLE
CANDLE Traveling Wave Reactor Engine producing no thrust

### ISSUE THREAD

**Issue by xdreaper15** [sswelm/KSP-Interstellar-Extended#264]
The CANDLE engine will stop producing any thrust or electricity after a random amount of time. Even if it wasn't on to begin with. Still has full Plutonium, and it even says the correct dV value, but as soon as you throttle up, it drops to 0 thrust and the console says StageInfo: Simulation time exceeded!
![KSP Candle](https://user-images.githubusercontent.com/6147395/54872572-64a0af80-4d9c-11e9-9e26-5890ccda9964.png)

**Comment by tomasbrod** [comment]
In reactor control window, it says that the reactor is offline. That is probably causing zero thrust. But why the reactor went offline, I do not know. You did not shut it down manually, right?

**Comment by sswelm** [comment]
The problem might be it is a bit too easy to shut down the engine. It could be accidentally triggered if you clicked another window above the shutdown button.

**Comment by xdreaper15** [comment]
I did shut it down, as I wanted to test conserving fuel for longer-term missions. Also, sometimes i like to use it as just an RTG, when the included solar power isn't enough. It happens then too.
