### ISSUE TITLE
Electric RCS does not work

### ISSUE THREAD

**Issue by tomasbrod** [sswelm/KSP-Interstellar-Extended#265]
Mounted Perpindicular Arcjet RCS. Engine starts with Is Powered: true, but as soon as I fire the RCS, it reverts to Is Powered: false. Toggling the Power button causes the Is Powered to flash to true, but immediately reverts to false. The ship has enough MegaJoules.

**Comment by sswelm** [comment]
By enough MegaJoules do you mean access to a reactor or only stored megajoules?

**Comment by tomasbrod** [comment]
After reading the source code, I now understand how the supply and demand behaves. And I was off by factor of 100.

**Comment by sswelm** [comment]
Yes they require a lot of power
