### ISSUE TITLE
AirIntakeAtm TORY Ramjet

### ISSUE THREAD

**Issue by gggorillaz** [sswelm/KSP-Interstellar-Extended#267]
Hi I don't actually know if this is an issue (or if it's more likely, user error) but I can't for life of me figure out what I'm missing with the TORY Nuclear Ramjet engine. I will flameout due to "Cause : IntakeAtm Deprived" continually, even when I have excess air intake warning levels.

I'm sure I have enough air intakes on my craft, and read somewhere that ramjet intakes don't activate until 20m/s, but I'll be in air at 150m/s and the air intake still remains at 0.9, drops to 0.0 and doesn't recover for the engines.

I've attached my .craft file that should illustrate this. Apologies if it's just my misunderstanding of functionality of the engine.
[Flyer-Mk_04.zip](https://github.com/sswelm/KSP-Interstellar-Extended/files/3077880/Flyer-Mk_04.zip)

**Comment by tomasbrod** [comment]
@gggorillaz I made a craft that works for me. Can you try it? https://kerbalx.com/tomasbrod/TORY-SpacePlane
