### ISSUE TITLE
Science Lab Research

### ISSUE THREAD

**Issue by Ireisme** [sswelm/KSP-Interstellar-Extended#270]
I was trying to figure out why my Science Lab was unable to generate any research and found this commit https://github.com/sswelm/KSP-Interstellar-Extended/commit/7c2fd161e3484422d1df96c3d09b38311c18a84e.

This looks like a pretty intentional change, but there is still a section on the wiki about using the Science Lab for research.

**Comment by sswelm** [comment]
Yes the wiki should be changed. Interstellar Science generation got replaced by stock research generation. It pretty much now function like a stock  science lab but with higher power requirement and larger science buffer to make late game science research less tedious.

**Comment by Ireisme** [comment]
Makes sense, thanks for updating the wiki as well 👍
