### ISSUE TITLE
Nuclear Turbojet atmo/velocity curves

### ISSUE THREAD

**Issue by tomasbrod** [sswelm/KSP-Interstellar-Extended#499]
I noticed that Direct Cycle Nuclear Turbojet uses atmosphereCurve and velocityCurve in ModuleEnginesFX instead of atmCurve and velCurve like rapier and other jets use. Then while testing I noticed that the trust drops way before intake air starts to drop. I want to ask few questions before messing with configs. What is the correct behaviour of the engine in relation to velocity and altitude?

**Comment by sswelm** [comment]
The config in the ModuleEnginesFX is not really using during normal KSPIE gameplay and is instead overridden by an internally defined atmosphereCurve and velCurve. This behaviour can be disabled by adding overrideVelocityCurve = false and overrideAtmosphereCurve  = false. It also overrides the acceleration and deceleration based on unlocked tech and engine speed. This can be disabled by overrideAccelerationSpeed  = false and overrideDecelerationSpeed = false

**Comment by tomasbrod** [comment]
So do I read it correctly that the engine has a second thrust peak at 800m/s which then drops quite sharply?

**Comment by sswelm** [comment]
Yes, that pretty much how it should works. The general idea is to make a distinction between the turbojet and the ramjet. THe Turbjojet would be really good at vertical takeoff, allowing to slingshot yourself into space while the ramjet would excel at High-speed High atmosphere propulsion, allowing you to gradually fly into orbit without any spend fuel.

**Comment by tomasbrod** [comment]
So why does the ramjet (tory) have the same velocity curve then? (also atmosphere curve, for that matter).

**Comment by sswelm** [comment]
That would just be the externally visible velocity curve. You are right that I should update it with the stats you get when fully upgraded.

**Comment by tomasbrod** [comment]
Again reading the source ([here](https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/FNPlugin/Propulsion/ThermalNozzleController.cs#L1204)) proved that this config entry is indeed not a bug.

**Comment by sswelm** [comment]
can this be closed?
