### ISSUE TITLE
CKAN Support

### ISSUE THREAD

**Issue by ruifung** [sswelm/KSP-Interstellar-Extended#5]
This mod does not appear to be available on CKAN for download, despite it's presence on SpaceDock/Curse.

**Comment by sswelm** [comment]
I'm wairting for Bizzy to update toolbar to 1.1.3

**Comment by sswelm** [comment]
Hopefully #this https://github.com/KSP-CKAN/CKAN-meta/pulls fix it

**Comment by ruifung** [comment]
I should say, that it's not being marked as incompatible - The mod isn't even showing up when I set the CKAN filter to All. (Mod name search: Interstellar or Mod author search: FreeThinker)

**Comment by politas** [comment]
That's due to KSP-CKAN/CKAN#1695, which we have tracked down, but have yet to code a fix for.
