### ISSUE TITLE
Cryo Tanks compatibility

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [sswelm/KSP-Interstellar-Extended#517]
I am very glad you made KSPIE compatible with Nertea's  CryoEngines and CryoTanks. However, IFS only allows you to fill tanks with hydrogen and oxygen, not hydrogen and oxidizer, which his engines require. In addition, the ability to fill tanks with hydrogen does not unlock at the same place in the tech tree as the engines themselves do, making them unusable at their intended tech level.

**Comment by sswelm** [comment]
LH2O was supposed to a Hydrogen Oxidizer mix used by Nertea's CryoEngines, but I now see it uses LqdOxygen instead. My bad

**Comment by sswelm** [comment]
Should have been fixed

**Comment by BTAxis** [comment]
I'm using Cryo Tanks via Cryogenic Engines, and I noticed the tanks do not consume EC for cooling, which they are supposed to do. It appears to be KSPIE's doing, because removal of the mod causes the tanks to consume EC as advertised.
