### ISSUE TITLE
Please update KJR to 3.4.1

### ISSUE THREAD

**Issue by syy1125** [sswelm/KSP-Interstellar-Extended#523]
KJR 3.4.0 used to create part connections across Breaking Ground robotic parts, causing them to get stuck. The Breaking Ground robotics are basically worthless with KJR 3.4.0.
KJR 3.4.1 fixes that issue.
Reference: https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued/pull/5

**Comment by sswelm** [comment]
thanks, that explains why so people were complaining that Robotic failed to function after instal of KSPIE (package)

**Comment by syy1125** [comment]
You forgot to close this.
