### ISSUE TITLE
(Suggestion) Add upgrades for the laboratory

### ISSUE THREAD

**Issue by Monniasza** [sswelm/KSP-Interstellar-Extended#524]
Hi, i am Monniasza. The laboratory only stores 1000 data and no more. Other parts support upgrades, but laboratory not. Maybe combine upgrades with laboratory and get better performance and capacity.
Possible capacities for data:
mk1: 1000
mk2: 4000
mk3: 16000
mk4: 64000
mk5: 256000

**Comment by sswelm** [comment]
that actually sound like a very good idea

**Comment by Monniasza** [comment]
Possible capacities for data:
mk1: 1000
mk2: 2000
mk3: 4000
mk4: 8000
mk5: 16000

**Comment by sswelm** [comment]
Alright, next release, both Data storage and scienceCap will increase from 1000 to 11390 but without increase research speed. Research speed grows proportional until 750 data is stored, after which that research speed remains constant. This effectively will make researching a lot less labour intensive while not magically increase the rate of generated science.

**Comment by Monniasza** [comment]
I proposed this change, because I ran out of Data storage on mun with cyclotron.

**Comment by Monniasza** [comment]
Please release update quickly.

**Comment by sswelm** [comment]
I haven't test it properly. Perhaps you can? I can release a alpha

**Comment by Monniasza** [comment]
Release alpha and keep thread open to look for feedback in this thread.

**Comment by Monniasza** [comment]
Is new alpha version out?

**Comment by sswelm** [comment]
Doing some  minimum testing to see if it actualy works

Op di 6 aug. 2019 om 19:48 schreef Monniasza <notifications@github.com>:

**Comment by sswelm** [comment]
https://www.curseforge.com/kerbal/ksp-mods/ksp-interstellar-extended/files/2756189

**Comment by Monniasza** [comment]
It works for me too, but vehicle assembly  preview shows incorrect value.

**Comment by sswelm** [comment]
it currently only becomes active during flight, I guess I can modify to be functional in the VAB as well
