### ISSUE TITLE
Solar Thermal Power Mirror Receiver not using shroud in flight

### ISSUE THREAD

**Issue by NachtRaveVL** [sswelm/KSP-Interstellar-Extended#533]
Noticed that when I tried to use this part in game, the shroud/fairing set up to be used in VAB did not correctly show when in-flight. This makes getting this piece into orbit pretty tricky, as it's incredibly unstable during the trip up. It's also not the most stable of piece when you do get it in orbit (had the kraken happen to me a few times already).

Using v1.22.5 with KSP 1.7.3, 64-bit, DX11.

**Comment by sswelm** [comment]
Alright, it will be fixed and improved next release
