### ISSUE TITLE
Vista Engine broken when used with Near Future Electrical

### ISSUE THREAD

**Issue by jswwww** [sswelm/KSP-Interstellar-Extended#54]
It looks like about a month ago the Vista engine controller was rewritten and the module renamed. At that time the Near Future patch wasn't updated with the new name. This can be resolved by adding the following to USI_NF_Mode.cfg:

```
@PART[*]:HAS[@MODULE[VistaECU2]]:NEEDS[NearFutureElectrical]:FOR[WarpPlugin]
{
	@MODULE[VistaECU2]
	{
		%powerRequirementMultiplier = 0.002
		%wasteHeatMultiplier = 0.002
	}
}
```

**Comment by sswelm** [comment]
thanks, I forgot all about that

**Comment by sswelm** [comment]
ok fixed
