### ISSUE TITLE
"PersistentThrust" preventing me from time warping

### ISSUE THREAD

**Issue by psychonaut25** [sswelm/KSP-Interstellar-Extended#543]
I don't have the PersistentThrust mod installed, and I've never installed it in the past... but for some reason when I attempt to time warp I receive the following message:

"Persistent thrust stopped - vessel not facing maneuver"

I reported this issue to bld over on the GitHub page for the PersistentThrust mod, and they pointed out that they had shared some code with the Interstellar Extended mod.  My next maneuver node is 2 years or so of game time away, so obviously I can't wait around for that in real time.

I'm running KSP 1.7.3 on Windows 7 Pro x64.

I performed a search in my GameData folder using JAM Software's Ultrasearch for any directories named "PersistentThrust" and found nothing.

Any suggestions?  I'm at quite a loss here.  I can provide log files if necessary.

Thanks

**Comment by sswelm** [comment]
Problem is fixed in 1.22.12. It available from
https://www.curseforge.com/kerbal/ksp-mods/ksp-interstellar-extended/files

**Comment by psychonaut25** [comment]
Confirmed.  Thanks so much sswelm!
