### ISSUE TITLE
Circular Solar Panels Block Themselves

### ISSUE THREAD

**Issue by PhilNorfleet** [sswelm/KSP-Interstellar-Extended#55]
The Circular Solar Photovoltaic Cells have an issue where they are always blocked by themselves, except when in the middle of animating the extending or retracting.

**Comment by davidson16807** [comment]
Problem goes if you set raycastTransformName = SunPivot in CircularSolarPhotovoltaicReceiver/CircularPanel.cfg. See pull request. I've tested in KSP 1.2 and see no obvious side effects.

**Comment by sswelm** [comment]
Good find

**Comment by arivaldh** [comment]
I have tested all circular panels. They seems to work fine now. It seems that @davidson16807 fix was spot on. Suggest closing the issue?
