### ISSUE TITLE
Bug in CryoTanksFuelSwitcher.cfg causes texture / render issues with CryoTanks

### ISSUE THREAD

**Issue by valderrama** [sswelm/KSP-Interstellar-Extended#551]
This is a copy of my comment in the KSPIE support thread [here](https://forum.kerbalspaceprogram.com/index.php?/topic/172026-181-173161151145-ksp-interstellar-extended-1252-support-thread/page/176/&tab=comments#comment-3727999).

**Overview**

I believe there is a bug in KSPIE/WarpPlugin [introduced by changes](https://github.com/sswelm/KSP-Interstellar-Extended/compare/97b75bc...09686f1) to [CryoTanksFuelTankSwitcher.cfg](https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/GameData/WarpPlugin/Patches/B9PartSwitch/CryoTanksFuelTankSwitcher.cfg) in v1.25.2 and [partially fixed](https://github.com/sswelm/KSP-Interstellar-Extended/compare/dfc507a...6d5bd08) in v1.25.4 that is affecting the [CryoEngines](https://forum.kerbalspaceprogram.com/index.php?/topic/106089-18x-cryogenic-engines-high-isp-chemical-rockets-updated-nov-6/) / [CryoTanks](https://github.com/ChrisAdderley/CryoTanks) mod.

**Symptoms**

CryoTanks textures fail to render properly, see screenshot:
![kspie-cryotanks-bug](https://user-images.githubusercontent.com/925981/72313487-5e880200-3640-11ea-949e-2ba474fa977c.jpg)

Possibly related error messages in the log regarding B9PartSwitch and CryoTanks:

```
[Part]: PartModule indexing mismatch at hydrogen-125-2, index 0.
Node 'ModuleB9PartSwitch' found in loaded data, but 'TweakScale' is defined in prefab.
Looking for ModuleB9PartSwitch in other indices...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

...ModuleB9PartSwitch module found at index 2.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[ERROR] [Part hydrogen-125-2] [ModuleB9PartSwitch 'fuelSwitch'] OnLoad was called with the wrong ModuleID and the correct module could not be found
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Part]: PartModule indexing mismatch at hydrogen-125-2, index 1.
Node 'TweakScale' found in loaded data, but 'USI_ModuleRecycleablePart' is defined in prefab.
Looking for TweakScale in other indices...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

...TweakScale module found at index 0.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Part]: PartModule indexing mismatch at hydrogen-125-2, index 2.
Node 'USI_ModuleRecycleablePart' found in loaded data, but 'ModuleB9PartSwitch' is defined in prefab.
Looking for USI_ModuleRecycleablePart in other indices...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

...USI_ModuleRecycleablePart module found at index 1.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Part]: PartModule indexing mismatch at hydrogen-125-2, index 3.
Node 'ModuleB9PartSwitch' found in loaded data, but 'ModuleCryoTank' is defined in prefab.
Looking for ModuleB9PartSwitch in other indices...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

...ModuleB9PartSwitch module found at index 2.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Part]: PartModule indexing mismatch at hydrogen-125-2, index 4.
Node 'ModuleCryoTank' found in loaded data, but 'ModuleB9PartInfo' is defined in prefab.
Looking for ModuleCryoTank in other indices...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Root Cause**

In the initial changes in 1.25.2 there were two different part node rules that contain the following deletion:
```
!MODULE[ModuleB9PartSwitch] {}
```

However in 1.25.4 only the first instance on line 25 was fixed with the following change:
```
!MODULE[ModuleB9PartSwitch]:HAS[#moduleID[fuelSwitch]] {}
```

**Solution**

To fix the issue [the second instance on line 171](https://github.com/sswelm/KSP-Interstellar-Extended/blob/f55e0d5a413c2931e35630f7c713cc9f9d91f01f/GameData/WarpPlugin/Patches/B9PartSwitch/CryoTanksFuelTankSwitcher.cfg#L171) must also have the HAS criteria added to the MODULE deletion.

After applying the fix and relaunching my game the textures now render properly and no errors related to B9PartSwitch and CryoTanks are observed in the log:
![kspie-cryotanks-fix](https://user-images.githubusercontent.com/925981/72313504-6ba4f100-3640-11ea-8991-dc6051c6e47a.jpg)

**Comment by sswelm** [comment]
fixed it with https://github.com/sswelm/KSP-Interstellar-Extended/commit/6f991970fad97af26e9b5d7e859c4f2d04679c31

**Comment by valderrama** [comment]
Thanks for the quick response. Your work is appreciated!
