### ISSUE TITLE
Oceans can never contain heavy water

### ISSUE THREAD

**Issue by tomforwood** [sswelm/KSP-Interstellar-Extended#554]
In OceanResourceHandler there is code which is supposed to add heavy water to any ocean that contains water.

However the code does this by checking if the ocean contains InterstellarResourcesConfiguration.Instance.Water which is initialised by warppluginsettings to LqdWater
The oceans themselves contain Water as initialised by community resource pack

As they don't match heavy water is never added to Kerbin's oceans

**Comment by sswelm** [comment]
Yes I noticed the exact same thing. I commited a fix which should solve the issue
