### ISSUE TITLE
Can't set a convertion ratio for Lithium Air Batterys

### ISSUE THREAD

**Issue by DoomOfMax97** [sswelm/KSP-Interstellar-Extended#557]
Hi,

I am not able to change the Convertion Ratio for Lithium Air Batterys,
to convert Kilowatt Hours into Electric Charge. The slider is gone.
I _think_ it has something todo with InterstellarResourceConverter.
It worked in the Version for KSP 1.7.3, but does not work in the Version for KSP 1.8.

Is this a bug or did something change?

**Comment by sswelm** [comment]
it was replaced by the FNBatteryGenerator partmodule which fully automates recharge and supply

**Comment by DoomOfMax97** [comment]
Ah I see, is there a way to increase the conversion rate, because I still run out of electric charge?
Or is this intended behavior, for example a fixed conversion rate?

**Comment by sswelm** [comment]
Yes, it is intended behavior, if you want more power add additional batteries. it is mainly intended for surviving blackout or to power electric pumped engines

**Comment by DoomOfMax97** [comment]
Ah okay, thank you!
