### ISSUE TITLE
5m orbital assembly docking port cannot dock with smaller ports

### ISSUE THREAD

**Issue by hvenev** [sswelm/KSP-Interstellar-Extended#566]
https://github.com/sswelm/KSP-Interstellar-Extended/blob/c334438a4ce5c65e5a218a5647a5a6ccc57088c8/GameData/WarpPlugin/Parts/Command/UnivDockPorts/UnivDockPort5m.cfg#L96

I think it should list all of the smaller sizes: `nodeType = size0,size1,size2,size3,size4`

**Comment by sswelm** [comment]
seems you are right
