### ISSUE TITLE
Core Temperature module is throwing a missing method exception

### ISSUE THREAD

**Issue by TheDirtyRag** [sswelm/KSP-Interstellar-Extended#568]
Version: Latest KSPIE release

Information: I encountered this bug using a compiled version when the April 29th commit was pushed a few hours before release. This bug is present in the release version. 

Description: Any Thermal Engine or has the option of using a thermal engine will throw an missing method exception that points to this. 

MissingMethodException: double FNPlugin.Redist.IPowerSource.get_MaxCoreTemperature()
  at FNPlugin.ThermalEngineController.EstimateEditorPerformance () [0x00011] in <976bd92cc12f4f4b8f072233b8db66f9>:0 
  at FNPlugin.ThermalEngineController.Update () [0x00007] in <976bd92cc12f4f4b8f072233b8db66f9>:0 

Proposal: I will see if adding the method to the namespace will fix the issue.

**Comment by sswelm** [comment]
I moved the method to the FNInterface, it should be fixed now
