### ISSUE TITLE
Antimatter collector "collection multiplier" not being applied.

### ISSUE THREAD

**Issue by DGerry83** [sswelm/KSP-Interstellar-Extended#57]
Tested using various tweakscaled AM collectors - the multiplier value is displayed in the UI but the collectors do not behave accordingly.  Possibly because "FixedUpdate" does not use the collectormultiplier value in its calculations?  If not I can't be any more helpful than to say the multiplier just doesn't apply.

**Comment by sswelm** [comment]
it was only applied on offline resource collecting on startup, but not to real-time collecting. Good catch
