### ISSUE TITLE
Tech level not affecting Data Processing Multiplier in science lab

### ISSUE THREAD

**Issue by milkdrinker7** [sswelm/KSP-Interstellar-Extended#578]
https://github.com/sswelm/KSP-Interstellar-Extended/blob/f52dc540590780488306676fb6b952f62dd79608/FNPlugin/Science/ScienceModule.cs#L282

 Here, you multiply and divide by moduleScienceLab.dataStorage which does nothing.  I suspect you meant to do something more sophisticated than multiply by 1 to reward higher tech tiers.

I won't presume how you mean to balance this, and I'm not really sure if issues are the place for suggestions, but something like this could probably work: after line 282, make dataProcessingMultiplier = dataProcessingMultiplier + (0.5 - dataProcessingMultiplier)*(X/6). Where 'X' is the amount of tech nodes augmenting the science cap unlocked. (so, zero before unlocking long term science tech, up to 6 after unlocking extreme high energy physics)

**Comment by sswelm** [comment]
well the idea is that while the amount of stored science is smaller than stock capacity, it should perform like stock science bay. The performance was intended to be  start improve after it recieved more than stock capacity limit of data.

**Comment by milkdrinker7** [comment]
Basically, line (282) can be simplified to
 : deminishingScienceModifier * (baseDataStorage / moduleScienceLab.dataStored) * 0.5f;
and it will do the exact same thing.
I know the additional speed after passing 750 data diminishes, I  guess I thought the upgrade tech nodes were supposed to lessen the rate of diminishing.

**Comment by sswelm** [comment]
Well, If you can make a pull request I will review it
