### ISSUE TITLE
incorrect boolean value

### ISSUE THREAD

**Issue by brustmopf** [sswelm/KSP-Interstellar-Extended#579]
Hi,
In the following files:
```
-GameData/WarpPlugin/Parts/Engines/ThermalTurbojet/ThermalTurboJet.cfg
-GameData/WarpPlugin/Parts/Engines/ThermalTurbojet/ThermalTurboJet2.cfg
-GameData/WarpPlugin/Parts/Engines/SAGE/KSPIE_SAGE.cfg
-GameData/WarpPlugin/Parts/Engines/ThermalAerospikeTurboJet/ThermalAerospikeTurboJet.cfg
-GameData/WarpPlugin/Parts/Engines/ThermalAerospikeTurboJet/ThermalAerospikeTurboJet2.cfg
-GameData/WarpPlugin/Parts/Engines/SURGE/OPT_SURGE.cfg
```

The trailing semi-columns in the section of code below causes an "Invalid boolean value!" error in the logs

        	overrideAtmCurve = true;
        	overrideVelocityCurve = true;
        	overrideAtmosphereCurve = true;
        	overrideAccelerationSpeed = true;
        	overrideDecelerationSpeed = true;
		

I tested without the semi-column... the error goes away, and the engine seem functional...

**Comment by sswelm** [comment]
good find
