### ISSUE TITLE
incorrect MethaneEngine isp in "Hydrazine-Oxidizer" mode

### ISSUE THREAD

**Issue by liyingcake** [sswelm/KSP-Interstellar-Extended#583]
The ChemicalEngine(title = #LOC_KSPIE_FNMethaneEngine_title)  have been set in wrong Isp number, Hydrazine-Oxidizer become 455s and it might not be that high.

cfg from stock
`   
    	MODULE
    	{
        	name = FuelConfiguration

        	fuelConfigurationName = Hydrazine-Oxidizer
		requiredTechLevel = 0
		hasIspThrottling = false
        	fuels = Hydrazine, Oxidizer
		typeMasks = 0, 0
        	ratios = 1.5, 0.1
		maxIsp = 455
		wasteheatMult = 1
        	thrustMult = 2.386
        	powerMult = 1		
		effectname = power_open
		neutronRatio = 0

		ignitionThreshold = 0.1
		exhaustDamageDistanceOffset = 0.19
        
        	atmosphereCurve
        	{
           		key = 0 455
            		key = 1 385
			key = 2 305
			key = 10 0
        	}
    	}

`

even high than methane-Lox type.

Change: copy wrong, I paste again

**Comment by sswelm** [comment]
seems like a copy paste mistake., what should it be in your opinion?

**Comment by liyingcake** [comment]
since stock Oxidizer are HTP, So we might change Hydrazine-Oxidizer `maxIsp = 455` to  `maxIsp = 340`  or lower, 

I cant find Hydrazine-HTP fuel now yet. But I remember most hypergolic fuel around 320s-340s

**Comment by liyingcake** [comment]
`    	ratios = 1.5, 0.1` and  `    	atmosphereCurve` are also need to change too.

**Comment by sswelm** [comment]
please review

https://github.com/sswelm/KSP-Interstellar-Extended/commit/afb79cf68d2302dcc20afb7e36b6b54adcf152ea

**Comment by liyingcake** [comment]
should be good, but I still have little doubts about the mix ratio but let have a shot

**Comment by sswelm** [comment]
I agree the ratio might not be right. Please advice
