### ISSUE TITLE
Support TETRIX Tech Tree

### ISSUE THREAD

**Issue by Monniasza** [sswelm/KSP-Interstellar-Extended#587]
KSP Interstellar Extended conflicts TETRIX Tech Tree by removing some nodes from the tech tree. The result is tree with broken pathways, nodes that lead nowhere, and missing nodes. And TETRIX nodes do not even appear.

Here's what tech tree should look like:![Go (here)[https://forum.kerbalspaceprogram.com/index.php?/topic/174731-19x-tetrix-techtree-25-and-simplex-techtree-116/page/11/&tab=comments#comment-3809380]](https://i.imgur.com/2HfCPvu.png)
An here's how it looks:![](http://u.cubeupload.com/Monniasza/howitisHETTN.png)

**Comment by sswelm** [comment]
did you keep your  TETRIXTechTree inside the AngleCanMods? if not, put it there

**Comment by theJesuit** [comment]
This could also be an issue with using HideTechTreeNodes being installed and uninstalled.

**Comment by sswelm** [comment]
Well I will add a rule just in case people put TETRIXTechTree in GameData

**Comment by Monniasza** [comment]
> did you keep your TETRIXTechTree inside the AngleCanMods? if not, put it there

Yes, because I installed it by CKAN.

**Comment by Monniasza** [comment]
> This could also be an issue with using HideTechTreeNodes being installed and uninstalled.
Yes, HETTN conflicts TETRIX Tech Tree, regardless if it is active or not.
Anyway, continue development.
