### ISSUE TITLE
Open gas core fission reactor fuel mode confusion

### ISSUE THREAD

**Issue by stasikos** [sswelm/KSP-Interstellar-Extended#59]
You have "Uranium Hexafluoride" in Reactor Control Window as fuel mode.
However, reactor itself has Uranium Nitride storage and still works. That seem quite confusing.
![imgur-2017_04_08-18 25 06](https://cloud.githubusercontent.com/assets/429948/24830156/fc3eac6c-1c88-11e7-9ec1-cce058655b3b.png)

Tested in 1.12.19 on KSP 1.2.2 with KER and VesselMover

**Comment by sswelm** [comment]
yes, it one of those lose end I never fully implemented. Thanks for reminding me.

**Comment by sswelm** [comment]
it can now use any nuclear fuel
