### ISSUE TITLE
Weird Graphical Issue when using radiators

### ISSUE THREAD

**Issue by enjoyingkspie** [sswelm/KSP-Interstellar-Extended#590]
I'm not entirely sure how to explain this issue, so I've included some screenshots to make the process easier.

When I try to use the attached ship, and launch from the Space Hangar, I get the attached graphical issue occurring.

![20200805213122_1](https://user-images.githubusercontent.com/69107221/89485544-5bbf4b00-d7e4-11ea-9ea4-2a468adef6ba.jpg)

[Untitled Space Craft.loadmeta.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/5032290/Untitled.Space.Craft.loadmeta.txt)
[Untitled Space Craft.craft.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/5032291/Untitled.Space.Craft.craft.txt)

If I remove the radiator and engines, I don't get the issue. If I remove just the engines and try to launch using the thermal rocket, I get the graphical issue.

When I try and use the tracking station view, I do not see any planets or other ships either. Sometimes, later on the game may crash,

This is a bit of a wierd issue. I don't have any other planet expansion mods installed. I'll continue trying different things to see if I can work out more about what the issue actually is.

**Comment by enjoyingkspie** [comment]
[KSP BUG.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/5032391/KSP.BUG.txt)
And the associated KSP.log. It doesn't look that useful though

**Comment by sswelm** [comment]
What is the graphical issue? I have no idea what this problem is and I have never heard from this before. So I think it unlicky related to KSP but rather some interaction with sthe stock partModules present on the KSPIE parts with another mod you have installed.

**Comment by enjoyingkspie** [comment]
The graphical issue is that screenshot should be the Airplane strip at KSC, not a black screen. It happens either straight after hitting the launch button, or sometimes after staging to launch the engines. 

As for other mods I have installed:

- Interstellar
- Kerbal Engineer Redux
- Global Construction
- Configurable Containers
- Mechjeb2
- ScanSAT
- Thrust Controlled Avionics
- X Science

I'm not sure which would be likely to be interacting with KSPIE in such a way.

**Comment by enjoyingkspie** [comment]
I managed to trigger the KSC / black screen disappearing upon starting engines again, and this time there was a useful log entry.

```text
[LOG 20:36:29.109] [TweakScale] WARNING: No valid member found for diameter in Part for <unk>
[LOG 20:36:29.136] [TweakScale] WARNING: No valid member found for maximumPowerGeneration in FNGeneratorAdapter for microwaveThermalEnergyReceiverM
[LOG 20:36:29.136] [TweakScale] WARNING: No valid member found for outputRate in FNGeneratorAdapter for microwaveThermalEnergyReceiverM
[LOG 20:36:29.136] [TweakScale] WARNING: No valid member found for inputRate in FNGeneratorAdapter for microwaveThermalEnergyReceiverM
[LOG 20:36:29.144] [TweakScale] WARNING: No valid member found for diameter in Part for <unk>
[LOG 20:36:29.171] [KSPI]: ThermalNozzleController OnRescale was called with factor 1.5
[LOG 20:36:29.172] [TweakScale] ERROR: Exception on Rescale: System.NullReferenceException: Object reference not set to an instance of an object
  at FNPlugin.ThermalEngineController.EstimateEditorPerformance () [0x00195] in <4e0ff788d78f47c787e8280dced5cbfc>:0 
  at FNPlugin.ThermalEngineController.OnRescale (TweakScale.ScalingFactor factor) [0x0004a] in <4e0ff788d78f47c787e8280dced5cbfc>:0 
  at TweakScale.TweakScale.CallUpdaters () [0x0012f] in <fe30b98943a242f997bae5d1715f2076>:0 
  at TweakScale.TweakScale.Setup () [0x000b1] in <fe30b98943a242f997bae5d1715f2076>:0  at error:0
[LOG 20:36:29.247] Untitled Space Craft loaded!
```

The "Object reference not set to an instance of an object" makes me think this is related to / duplicate of https://github.com/sswelm/KSP-Interstellar-Extended/issues/589

[KSP BUG 2.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/5047256/KSP.BUG.2.txt)


I'm using the latest version of tweakscale for what it's worth.
