### ISSUE TITLE
Ground based WasteHeat removal systems

### ISSUE THREAD

**Issue by JamesJVillalta** [sswelm/KSP-Interstellar-Extended#591]
Hello,

Thank you for developing Interstellar Extended, it's a lot of fun and has been a source of a lot of learning for myself, and I suspect a lot of other people.

Just thought I'd share some random late night thoughts. 

While designing a base on Mun (using Global Construction, and KIS/KAS) with some nuclear reactors for beamed power generation (self sustaining by mining the required resources in-situ and processing them), I thought it would be more visually appealing (and perhaps more realistic) to  have less external radiators present to deal with the waste heat generated. 

I started doing some reading online about geothermal heat pumps, and found http://www.thermopedia.com/content/837/ - this looks useful for some maths behind the system, and some of the chemicals they use (plain water, air, hydrofluorocarbons ). HFC's are apparently a global warming problem though :)

https://www.automaticheating.com.au/complete-guide-to-heat-pumps/all-change-new-refrigerants-in-heat-pumps/ came up in a search about it - it seems that CO2 is suitable as well. Presumably the different chemicals have different thermal properties, and as such can be used for varying levels of effectiveness (along with your standard technical upgrades available).

From a glance over http://www.hydrocarbons21.com/articles/mayekawa_develops_high_temperature_hydrocarbon_steam_heat_pump it seems to indicate a 75% effectiveness (COP) score is possible.

On planets / moons with an IntakeLqd source, an additional cooling approach might be to have a component that uses the IntakeLqd and produces steam from it - reducing the drill that takes Water / IntakeLqd, and visually outputs steam. https://physics.stackexchange.com/questions/44591/can-traditional-steam-water-vapour-exist-in-a-vacuum seems to suggest that the water would continue to evaporate until an equilibrium is reached between liquid and gas states. I recall reading that drilling doesn't affect the resources in that location (nor the planets mass), so we can assume infinite intakelqd, thus obviously we have an infinite gas state :)

https://www.businessinsider.com/nasa-apollo-astronauts-warmed-the-moon-2018-6 also came up in a search about it, when trying to find out temperature ranges of the moon's crust.

A non-huge radiator wasteheat removal system would be nice for planet bases, and looks reasonable from what I can understand. I might look at modding guides and C# more to try and understand how much difficulty it would be. I have many learning curves before I could implement this, such as balancing the resulting game play, how graphics work, etc.

**Comment by sswelm** [comment]
Interesting idea, I could add a specialed radiator function to the Universal Drill

**Comment by JamesJVillalta** [comment]
Thank you, that will be much appreciated. 

In case you run into an issue with bases jumping around when coming out of warp, I've seen three work arounds. (The base was on the flats of Minmus - no incline in sight).

One is to use the rocket clamp to hold bases in place, and the second is to use a "ground tether" from USI Tools (https://forum.kerbalspaceprogram.com/index.php?/topic/133606-110x-kerbal-planetary-base-systems-v1612-14-july-2020/page/96/  - check for USI_InertialDampener).  There is also the cement block 1 from KAS.

The KAS cement block 1 seems broken to me and doesn't work correctly. 

The rocket clamps do not necessarily work very well for base design, I've seen some issues with it. I think due to auto-struct and struct to the heaviest component changing.

The USI tools approach seems to work alright so far for me. https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/blob/7c45149089cd8361db711c217e6f97543b1e7f18/USITools/USITools/ModuleStabilization.cs and https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/blob/87c98c8bccc363b7af495b3955ce6d67027d936c/USITools/USITools/USI_InertialDampener.cs seem relevant.

Would it be possible to implement a similar work around as USI tools for the drill when being used for cooling? (Not necessarily all the time - landing with an extended drill would perhaps look unrealistic)

Thank you for listening :)

**Comment by JamesJVillalta** [comment]
Would it be possible to have the beamed power senders (e.g. "Multi Bandwidth Dish Transceiver") expose/use the electrical priority system? (Rank in the Megajoules Management Display)

The "Multi Bandwidth Dish Transceiver" has a priority of 2, and the "Large Deployable Auger" has a priority of 4. It seems that I need to click on on the drill multiple times until it starts properly. It displays the "Not enough power to run the universal drill" message. Sometimes the drill turns itself off with "Not enough power to run the universal drill". It's connected to two 80GW reactors, so it's not a lack of power that's the issue :)

I would prefer the beamed power senders to be last in terms of power demand, as the drill is used for mining fluorine, which makes Th4F, which makes Uranium Nitrite, which powers the drill. The remainder of the power can be used for the rest of the solar system.

A work around (that I can live with) is to use beamed power for the drills / refinery instead.
