### ISSUE TITLE
FL-T fuel tanks rapid argon boiloff

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#594]
KSP 1.10.1.2939
KSPIE 1.25.24
IFS 3.18
IFSC 3.18
MM 4.1.4

FL-T series tanks such as the FL-T800 have strange boiloff.
Liquid Hydrogen and Liquid Methane appear to be normal. Some electrical drain for cooling, and some boiloff when uncooled.

Liquid Argon vaporizes instantly. It refuses to use any electricity, and inspecting the part indicates that there's a boiloff rate of a rather impressive 22394.7 L/s, meaning that the tank will be empty the moment you load onto the launch pad.
The exact boiloff rate appears to vary run-to-run.

The ship used is 2 parts. Z-200 battery bank tweakscaled to 2.5m so it has 12800 EC, and an FL-T800.

**Comment by sswelm** [comment]
Found the problem, the where power and boil off rate were mixed up.
