### ISSUE TITLE
Magnetic Scoop Atmosphere Hydrogen collected

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#595]
KSP 1.10.1.2939
KSPIE 1.25.24
IFS 3.18
IFSC 3.18
MM 4.1.4

Magnetic Scoop "Atmosphere Hydrogen collected" behaves poorly. It's significantly faster than the tooltip text in-flight, and also doesn't scale with time warp.

Test spaceship uses a Quantum Singularity Reactor as power source, 2 of Magnetic Scoop, and a scaled-up Cyclotron Antiproton Factory as a power sink. Orbit is around Kerbin, 3062.5km periapsis, 3063.6km apoapsis.

At maximum output, the QSR consumes 512.7g/hr of hydrogen, and also produces 25.6g/hr, solar wind processing produces 37g/hr. Atmosphere Hydrogen collected should be 1276.3g/hr according to the tooltip, but is visibly at least 30g/s, or 108000g/hr.

This excessive production is vaguely balanced out by the fact that it doesn't scale with time warp, effectively dividing it by the current time warp factor. At 100x time warp, the collection rate is still significantly higher than consumption, but there's a noticeable difference. At 1000x time warp, the collection rate is now below consumption.

**Comment by sswelm** [comment]
Found that resource collected for Hydrogen and Helium wasn't linked to time. Now it does. It should be fixed next release
