### ISSUE TITLE
When there is a group of landed vessels within the local physics simulation, the universal drill uses the resource abundances of the location of the focused vessel instead of those of its own location. 

### ISSUE THREAD

**Issue by cbohrson** [sswelm/KSP-Interstellar-Extended#597]
On KSP 1.9

Suppose we have vessels A and B.  Vessel A is in highlands and B is in midlands, and both are located together on the border between the two biomes within local physics (< ~ 2 km apart).  Highlands has water but no salt, midlands has salt but no water.  Only A has a drill.

The behavior I expected was that regardless of vessel focus A collects water, but no salt. 

What I see is that if B is focused, A collects salt, and if A is focused, A collects water.

**Comment by JamesJVillalta** [comment]
From looking at the code, I can see how what you're describing could happen.

https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/FNPlugin/Collectors/UniversalCrustExtractor.cs#L677-L695

As for fixing it, I'll think about what's possible. Perhaps there is a way to go from part -> vessel -> current location, as opposed to using the global variables to get the current vessels location
