### ISSUE TITLE
IXS Magnetic Confinement Fusion Reactor no longer allowed to fuse Deuterium - Lithium6

### ISSUE THREAD

**Issue by NachtRaveVL** [sswelm/KSP-Interstellar-Extended#60]
Maybe this was intentional, but I noticed that the IXS fusion reactor no longer allows fusing of De-Li6, as it was able to do in prior incarnations of KSP-IE.

I also noticed it doesn't allow He3-He3 fusing, amongst a few of the other fusing modes that things like the Stellarator and such allow (but maybe that's also intentional?).

Apologies if my ignorance of fusion reactions proceeds me. :p

**Comment by NachtRaveVL** [comment]
Also modifies the radiator maximum dissipation setting in some odd way, causing one to have to use way more radiators than the heat it actually produces.

**Comment by arivaldh** [comment]
I'll look into both issues.

**Comment by arivaldh** [comment]
All modes are present. However there's indeed a problem with extremely high WasteHeat production. Please look at:
https://imgur.com/KVwMzX4
He3-He3 mode, so no thermal power - charged power only. 13% active on 90% efficiency should give 65MW wasteheat. For some reason it produces 3.5GW of heat.
@sswelm do you have any ideas?

**Comment by sswelm** [comment]
I suspect it is caused by the maintenance wasteheat combined with a mixup of fixed time with power per second

**Comment by sswelm** [comment]
Yep, confirmed and fixed
