### ISSUE TITLE
Liquid Metal Cooled Reactor upgrade tooltip

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#609]
KSP 1.10.1.2939
KSPIE 1.25.26

The tooltip for mk9 upgrade for Liquid Metal Cooled Reactor lists 0% efficiency. In testing this is not the actual efficiency that ends up being used, it appears to fall back to the mk8, which is reasonable behavior, but the tooltip does not reflect this. If the mk9 upgrade does nothing, is the entry even needed?

**Comment by JamesJVillalta** [comment]
Can you attach a screen shot of the mk9?

I think something broke in your installation, as I only see up to mk3.

**Comment by embermctillhawk** [comment]
Sorry, to clarify, I mean the efficiency upgrades for the built-in thermal generator. Power output has 3 tiers and appears normal.
![image](https://user-images.githubusercontent.com/23393595/94209762-500a0f80-fe8a-11ea-81bf-bdbfc821bb84.png)

**Comment by sswelm** [comment]
good catch, I will fix it
