### ISSUE TITLE
Vista Fusion Engine exhaust not aligned with centerline of engine.

### ISSUE THREAD

**Issue by CitizenJoe** [sswelm/KSP-Interstellar-Extended#61]
The thrust the Vista produces doesn't seem to pass through its centerline and even causes craft that are perfectly symmetrical to yaw/pitch quite significantly during a burn, even causing misalignment with SAS enabled

**Comment by arivaldh** [comment]
I have tested it. It either was an issue, but was fixed or there wasn't an issue to begin with. Please confirm.

**Comment by sswelm** [comment]
I was puzzled by this one too. I guess it was something completely unrelated. closing for now
