### ISSUE TITLE
Some antimatter containers extremely expensive while empty.

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#616]
KSP 1.10.1.2939
KSPIE 1.25.27

`AntiProton Bose Einstein Condensate (AP-BEC-3)` costs $6,029,999, empty.
With tech level 5, it can store 60,000 units of Antimatter, at which point it costs $12,030,000.

I believe the $12,030,000 while full is intended. I do not believe the $6,029,999 while empty is. The cost line in the file says

`cost = 12030000	// 30000 + 100 * 120000 = 12030000`

Which would indicate that the cost should be more like $30,000 empty.

`Electrostatic Antiproton Storage Ring` costs $1,006,875 empty. With tech level 3, it can store 31.25 units of Antimatter, which brings the total to $1,010,000.

`Electrostatic Particle Trap (CPT2501)` costs $10,000 empty. It can store 500 units of Antimatter, which brings the cost up to $60,000.

Either the AP-BEC-3 is wrong, the Storage Ring is extremely wrong, and the CPT2501 is normal, or the reverse is the case.

**Comment by sswelm** [comment]
Good point, I will augment the antimatter storagepartmodule to modify the cost of the tank depending on the maximum storage

**Comment by sswelm** [comment]
I think I fixed it with https://github.com/sswelm/KSP-Interstellar-Extended/commit/5f2c8be84129c690401cccb1631a4ca7d29595af

**Comment by embermctillhawk** [comment]
I don't know if that fix was included in 1.25.28 or not, but, after updating to 1.25.28, the behavior is still present, with one odd exception.

If the AP-BEC-3 is the first part placed, then it will cost $30,000. Adding any other part to the craft or changing the amount of antimatter or hydrogen in the tank or will revert the cost to $6,030,000. Notably, rescaling the part does not break the cost.

**Comment by sswelm** [comment]
I notice if you scale the container, it gets the correct value, only if you add it, it has the wrong value

**Comment by sswelm** [comment]
Alright, I figured KSP start to behave weirdly when you lower the maximum resource, which only happens when the part isn't fully upgraded. Could you please test with the latest dll at https://github.com/sswelm/KSP-Interstellar-Extended/tree/master/GameData/WarpPlugin/Plugins

**Comment by embermctillhawk** [comment]
Testing with the latest DLL, seems to work fine now for tech 5.
Started a test save and gave enough science to buy Extreme Fuel Storage but only have tech 1, works fine as well. Nice.

**Comment by embermctillhawk** [comment]
Behavior regression;

Cyclotron Positron Factory
KSPIE "Sage"
Cyclotron Antiproton Factory
Deployable Antimatter Collector
Fixed Antimatter Collector
RV Antimatter Penning Trap

All of these now become strongly negatively priced when set to large scales.
