### ISSUE TITLE
Plasma Jet Magneto Inertial Fusion Reactor oddities

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#617]
KSP 1.10.1.2939
KSPIE 1.25.28

`#LOC_KSPIE_PlasmaJetMagnetoInertialReactor_descr` is used by the PJMIFR but the contents are identical to `#LOC_KSPIE_FURMagTar_descr` for the Magnetized Target Fusion Reactor.

Also, the fuel modes start at Mk-1, then go to Mk0, then go to Mk1 and 2 and onwards.

**Comment by sswelm** [comment]
sorry, I don't get what you are saying

**Comment by embermctillhawk** [comment]
![image](https://user-images.githubusercontent.com/23393595/94875379-e0f46400-0411-11eb-8912-c0d288401cf6.png)
![image](https://user-images.githubusercontent.com/23393595/94875400-f8cbe800-0411-11eb-86c3-3f794b4ff9ed.png)
The descriptions for these parts are the same despite being different parts that are fundamentally incompatible (one uses thermal nozzle only, the other is plasma nozzle only)

![image](https://user-images.githubusercontent.com/23393595/94875459-1f8a1e80-0412-11eb-8415-0d9a481b0ab0.png)
The fuel modes start at Mk-1 with the PJMIFR.

**Comment by sswelm** [comment]
Alright, all reported issues should be fixed in next release
