### ISSUE TITLE
Tritium-Tritium fusion mode unusable

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#618]
KSP 1.9.1.2788
KSPIE 1.25.30

Despite having all tech nodes researched, and 2 tons of tritium onboard, tritium-tritium fusion cannot be selected in the reactor control window.

Test craft appears to be able to select all other fuel modes for each reactor that each has listed, such as deuterium-tritium, but not tritium-tritium.
![image](https://user-images.githubusercontent.com/23393595/95519865-43ee7980-0983-11eb-8e70-d7e364fb316e.png)

**Comment by sswelm** [comment]
Exactly what reactor are you using?

**Comment by embermctillhawk** [comment]
All of the following:

Magnetized Target Fusion Reactor
MFC Spherical Tokamak
Plasma Jet Magneto Inertial Fusion Reactor
Stellarator Fusion Reactor

**Comment by embermctillhawk** [comment]
![image](https://user-images.githubusercontent.com/23393595/95624015-6d66de00-0a33-11eb-99bf-ab2c2d4868da.png)
For context I was making a spreadsheet of most of the fusion modes (i left a few out deliberately) and the ratios at which they consume and produce various resources and that's how I noticed that tritium-tritium wasn't selectable for some reason, which is why it's currently not in my spreadsheet.

**Comment by sswelm** [comment]
I suspect its some safety feature that kicks in to prevent the engine for choking itself

**Comment by embermctillhawk** [comment]
I just tested. Even if only tritium is available, the reactor won't run T-T.

Also, while testing that, I found that the Magnetized Target Fusion Reactor actually doesn't have all the modes as listed in the part info. With further testing, it only has 4 modes. `D-T`, `cold D-D`, `D-D`, `he3 catalyzed D-D`. I think it's because all the modes that are listed in part info but don't actually work are largely Charged Particle reactions but the MTF can only use Thermal modes.

**Comment by sswelm** [comment]
Well I do remember there are some min and max neutronic constraint on some reactors, also it the fusion mode produces too little power it might be constrained at low tech levels. Did you test in sandbox on campaign/science mode

**Comment by embermctillhawk** [comment]
Tested in both campaign and sandbox. And yes, I made sure to check the "enable part upgrades" in game settings for sandbox.

**Comment by embermctillhawk** [comment]
I checked `WarpPlugin\Resources\ReactorFuels.cfg` and I think it might be neutron constraints as you mentioned. D-T has the highest neutron ratio out of almost any of the reactions at a `0.8`, but T-T has a ratio of `3.2398`

**Comment by sswelm** [comment]
Then we have our solution. Fix that number. I  believe it should be 0.833

**Comment by sswelm** [comment]
Fix in https://github.com/sswelm/KSP-Interstellar-Extended/commit/eb3096847cdf3289f5e97ba1db935a5279dc0ea2

**Comment by sswelm** [comment]
btw, I noticed Tritium-Helium3 Fusion is missing. I guess I could add it

**Comment by sswelm** [comment]
Did it work well now it the latest beta?

**Comment by embermctillhawk** [comment]
How to access latest beta?

**Comment by sswelm** [comment]
https://www.curseforge.com/kerbal/ksp-mods/ksp-interstellar-extended/files

**Comment by embermctillhawk** [comment]
Tritium-Tritium and Tritium-Helium3 are selectable in all 4 discussed reactors in the 1.26.3 beta

**Comment by sswelm** [comment]
so we can close it?

**Comment by embermctillhawk** [comment]
Aww, but I like talking to you.

(yes, I'll close it now)
