### ISSUE TITLE
Thermal Turbojet Short inexplicably high drag

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#622]
KSP 1.10.1.2939
KSPIE 1.25.31

Ferram Aerospace is not in use currently.

For some reason the Thermal Turbojet Short gets extremely high drag.

![image](https://user-images.githubusercontent.com/23393595/95926905-ab893800-0d7a-11eb-8d8c-3ac84805b3c1.png)
Here is the craft in question.
![image](https://user-images.githubusercontent.com/23393595/95926932-be9c0800-0d7a-11eb-8281-9974e006a474.png)
Here is the drag debug data for the turbojet.
![image](https://user-images.githubusercontent.com/23393595/95926956-cc518d80-0d7a-11eb-9b0a-2be21a2056f6.png)
Here is the drag debug data for the shock cone intake in front of it.

I have no idea what any of these numbers mean other than "thermal turbojet short has a drag value 500 times higher than the shock cone at the front" which to me makes absolutely no sense.

For reference, the main body is in standard Mk3 scale, and the engine stacks at the sides are in 1.875m scale.

**Comment by sswelm** [comment]
I think the drag cube is all wrong

**Comment by embermctillhawk** [comment]
Removing the drag cube dramatically improves the performance of the craft in lower atmosphere, and the drag value in the debug menu is now less than but still proportional to the drag value for the shock cone intake.

**Comment by sswelm** [comment]
it is still too high?

**Comment by embermctillhawk** [comment]
I am unqualified to give a definitive answer but a drag value of consistently around 1/3rd of the intake at the front seems consistent with the aero behavior of the rest of the craft.

That reminds me, I need to go check up on the radiant drive cuz iirc it did something similar...

**Comment by embermctillhawk** [comment]
I have found that the radiant drive suffers similarly in-atmosphere. Should I open a new issue for that or just post it here?

**Comment by sswelm** [comment]
Well I think we can apply the same logic for any engine. The antimatter radiant drive isn't particular streamlined is design. Does removing the  Drag Box improve it?

**Comment by embermctillhawk** [comment]
The radiant drive probably shouldn't be exceptionally aerodynamic, but, the specified drag box seems excessive.

![image](https://user-images.githubusercontent.com/23393595/96502308-d528e000-120e-11eb-9c8f-d8d05589502a.png)
This is the test craft for the radiant drive in flight.
![image](https://user-images.githubusercontent.com/23393595/96502364-e8d44680-120e-11eb-996c-79c489e5002d.png)
This is a screenshot in the VAB so you can more clearly see the size relationship between the metal plates added and the radiant drive.

![image](https://user-images.githubusercontent.com/23393595/96502491-17eab800-120f-11eb-8758-18588623874c.png)
This is the drag data in-flight for the metal plates.
![image](https://user-images.githubusercontent.com/23393595/96502606-449ecf80-120f-11eb-8a72-fe06d571dd5a.png)
This is the drag data in-flight for the radiant drive.

From here it seems that the radiant drive which is inline with the body of the craft and not excessively wide (except for the fin things sticking out the bottom) has almost 7 times the amount of drag as literally just a flat chunk of metal that one could reasonably use as an aerobrake slapped onto the side of the craft.

**Comment by sswelm** [comment]
and after you remove the drag cube from the config file?

**Comment by embermctillhawk** [comment]
Sorry, life got in the way for a bit. sister had a wedding.

Anyways,

![image](https://user-images.githubusercontent.com/23393595/97239267-c57e3e00-17b0-11eb-97e9-97d59e85db03.png)

So now it gives about twice the drag drag of the command pod up at the top, which intuitively makes sense to me just looking at the rocket.
