### ISSUE TITLE
Graphene Umbrella Radiator Borked

### ISSUE THREAD

**Issue by NachtRaveVL** [sswelm/KSP-Interstellar-Extended#64]
The deployment modes on the umbrella radiator, especially in regards to automation, seem borked. This may be in relation to receiver dishes (since the Circular Thermophotovoltaic Receiver also seems weirded out similarly, albeit differently).

In previous versions, the umbrella radiator would, for instance, when automation is enabled, open up after leaving atmosphere. It would also automatically close upon liftoff (if opened), as well. Neither of these work anymore.

Additionally, if the radiator/automation/deployment modes aren't selected properly in VAB, upon liftoff the radiator won't animated that it has opened but will act like it has opened from liftoff (causing launch speed to drop, as it should when opened).

I also noticed that there are repeated actions available for this part, and some of the actions, when mapped, don't actually work.

**Comment by arivaldh** [comment]
I see that there is indeed some problem.
Automation toggles are visible only in editor (and only once. Reloading vehicle hides those. In Flight they're also not available.
I can also see that there is no Deployable Radiator module for it.
//animName = extendShield (is commented).
I don't have a clear idea what to do.

**Comment by arivaldh** [comment]
@sswelm  I will need your assistance here. Please guide me a little and I will fix this part.

**Comment by sswelm** [comment]
There are 2 part module that control this part, which is the MicrowaveReceiver and Radiator. Both have a form of automation which might interfere with each other. The way to solve it is that one need to take control why the other becomes a slave. There should already be this behaviour be for some reason It doesn't work anymore as it supposed to.

**Comment by arivaldh** [comment]
That's quite a lot of info. I'll look into it.

**Comment by arivaldh** [comment]
It seems that the info was correct. Microwave power received does override Radiator automation. But it doesn't have automation of it's own - or rather automation is one way - only enables when possible. Won't disable if dangerous conditions are present. Automation toggles are also not visible once Radiator toggles are disabled.
