### ISSUE TITLE
Proton-Proton fusion missing solid hydrogen variant

### ISSUE THREAD

**Issue by embermctillhawk** [sswelm/KSP-Interstellar-Extended#642]
KSP 1.10.1.2939
KSPIE 1.25.31

Proton-Proton fusion is missing solid hydrogen variant.

A vessel with hydrogen, liquid hydrogen, and solid hydrogen, and a reactor for p-p and one for p-p-p will function as expected until the hydrogen and liquid hydrogen is depleted.

When only solid hydrogen remains, the p-p-p reactor will continue operating but the p-p reactor will complain that there is no hydrogen remaining.

**Comment by sswelm** [comment]
Should be solved now
