### ISSUE TITLE
Scaling Up Microwave Phased Array Transceiver Lowers Mass

### ISSUE THREAD

**Issue by NachtRaveVL** [sswelm/KSP-Interstellar-Extended#65]
Scaling this part up, along with the deployable phased array, causes the total mass to decrease instead of increase.

Maybe a missed negative sign?

**Comment by arivaldh** [comment]
I don't know which part is that right now. @sswelm could you confirm that the issue is still valid?

**Comment by sswelm** [comment]
I will look into it

**Comment by sswelm** [comment]
Seems to work find to me, going to close it
