### ISSUE TITLE
IXS Hidden

### ISSUE THREAD

**Issue by irontom10** [sswelm/KSP-Interstellar-Extended#660]
The reactor is currently hidden. Would like to make a ship using said reactor in my career save. If possible to re-enable the reactor how would one do so.

https://github.com/sswelm/KSP-Interstellar-Extended/wiki/IXS-Magnetic-Confinement-Fusion-Reactor

**Comment by sswelm** [comment]
to make is visible again, open WarpPlugin\Parts\Electrical\IXSMainHull\MainHull.cfg, remove "TechHidden = True" and change "TechRequired = hidden" to "TechRequired = advFusionReactions"

**Comment by irontom10** [comment]
Thank you sir!
