### ISSUE TITLE
Data display issues in the engine's right-click menu

### ISSUE THREAD

**Issue by muse90673** [sswelm/KSP-Interstellar-Extended#662]
The thrust and ISP data are not displayed correctly in the engine's right-click menu, and the MechJeb2 panel and Staging Stack have the same problem. Without this information, it would have taken more time to design the vehicle.
KSP Version: 1.10.1
MOD Version: 1.26.7
![screenshot1](https://user-images.githubusercontent.com/38189037/102607691-a625e080-4163-11eb-8d84-30656d558795.png)
![screenshot2](https://user-images.githubusercontent.com/38189037/102607773-d4a3bb80-4163-11eb-8919-1220679dddbe.png)

**Comment by sswelm** [comment]
issues should ve been solved
