### ISSUE TITLE
Beam Receiver receives incorrect power

### ISSUE THREAD

**Issue by muse90673** [sswelm/KSP-Interstellar-Extended#663]
When I was testing the receiver, I found that the power received by the receiver is incorrect. 

As shown below, Network Power * Network Efficiency is not equal to Available Power(3.703*0.8716=3.228, not 1.980). When I click on the "Disable Receiver" button, the Available Power number becomes correct. After clicking the "Activate Receiver" button, the Available Power number becomes incorrect again.
KSPI-E version is 1.26.7, running on KSP 1.10.1

![from1 26 7](https://user-images.githubusercontent.com/38189037/102692127-2fb0dd80-424c-11eb-961d-eb75e20e6d39.png)

For comparison, I tested the same configuration of the craft in 1.24.3.5 KSPIE and the Available Power number is correct:

![from1 24 3 5](https://user-images.githubusercontent.com/38189037/102692349-ae5a4a80-424d-11eb-8535-682aed0ce7be.png)

**Comment by muse90673** [comment]
I have also tested other kinds of transmitters and receivers, still same problem.

**Comment by muse90673** [comment]
I just re-tested beamed power in the latest version of KSPIE(1.26.12), using the same configuration of the ship as before, and had the same problem as before. It looks like beamed power is not being fixed correctly. @sswelm

**Comment by sswelm** [comment]
seems to me this is a display issue rather than a logical error because there are multiple inefficiencies at work that affect the final received power. There are 2 main efficiencies, which are network inefficiency (caused by the actual transmission) and beam to wall inefficiency (where the beam is converted into electrical power). What is going wrong here I think is that the final beam to wall inefficiency isn't properly applied at all times.

**Comment by sswelm** [comment]
Notice there is also something called atmospheric efficiencies which isn't properly displayed, but does affect the overal available power. It depends on the angle of the beamed, the wavelength and moisture in the atmosphere.

**Comment by muse90673** [comment]
> seems to me this is a display issue rather than a logical error because there are multiple inefficiencies at work that affect the final received power. There are 2 main efficiencies, which are network inefficiency (caused by the actual transmission) and beam to wall inefficiency (where the beam is converted into electrical power). What is going wrong here I think is that not all inefficiencies are properly applied at all times.

@sswelm 
I don't think it's just a display issue.
I did a new test, to exclude atmospheric interference, with two spaceships in orbit (transmitter and receiver) and they are tens of km apart. [Figure1]

1. From the transmitter [Figure2] , **wall to beam power** value has been multiplied by the conversion efficiency, and **network power** is equal to **wall to beam power**.
2. From the beam transmission path, no atmospheric interference, meaning no loss
3. from the receiver [Figure3] , **spot size** is much smaller than the receiver diameter, 100% facing, the receiver's **power capacity** is greater than the **network power**, so it should be able to get all the energy (not considering the receiver efficiency).
4. **power receiver interface** shows 100% **network efficiency** [Figure3] , if this value is only related to atmospheric loss, receiver diameter to spot size ratio, facing, then this value should be correct

If there are no other interference factors, then the actual available power of the receiver should be equal to **network power** * **network efficiency** * **receiver efficiency**, which is **total current beamed power** in the **power receiver interface**.

However the actual **available power** (total current beamed power = available power * receiver efficiency) is not equal to the calculated value, about half of it [Figure3] . I don't think there is any other inefficiency in the transmission process.
I also don't think this formula is wrong, because I try to adjust the receiver facing, so that **facing** value gradually reduced to 0%, and then **network efficiency** will drop. At first **available power** will not drop with **network efficiency**, however, when **network efficiency** down to about half, **available power** began to drop, now the **available power** is equal to the above formula calculation value.

So I think some unknown factor makes **available power** can't be greater than half of **network power**, maybe it's a logic error in the code, or maybe it's something else.
And I don't see the above problem in the 1.24 version of kspie, this problem seems to appear from some sub version of 1.25.

Figure1
![two_vessels](https://user-images.githubusercontent.com/38189037/103896548-1dc8a900-512d-11eb-995d-3aab3b66c82a.png)

Figure2 Transmitter
![transmitter](https://user-images.githubusercontent.com/38189037/103896635-3f299500-512d-11eb-8f21-26d619ebafa8.png)

Figure3 Receiver
![receiver](https://user-images.githubusercontent.com/38189037/103896660-4650a300-512d-11eb-999f-07e7bf419a48.png)

**Comment by sswelm** [comment]
Problem identified and solved in 1.26.15

**Comment by muse90673** [comment]
> Problem identified and solved in 1.26.15

Great! Glad it's back to normal
