### ISSUE TITLE
Sciencelab unable to transmit generated science (fix included)

### ISSUE THREAD

**Issue by xDeerStalker** [sswelm/KSP-Interstellar-Extended#667]
Hello,
there is a new bug related to transmitting science from the science lab. 

What:
Basically the same described [here](https://forum.kerbalspaceprogram.com/index.php?/topic/182402-science-lab-not-transmitting/) 

Cause: commit 3c2756165a8800ed4d4f1a132e3c1409d980a150
File: GameData/WarpPlugin/Parts/Command/scienceModule/part.cfg
Reason: containerModuleIndex = 0 // line87
 -> The "0th" MODULE isn´t a ModuleScienceContainer anymore, since the patch introduced a MODULE NuclearRefineryController on the 0th position.

Fix: Move the NuclearRefineryController MODULE node further down in the file 
or change 
containerModuleIndex = 0
to
containerModuleIndex = 1

**Comment by sswelm** [comment]
could you make a pull request with the proposed changes?

**Comment by xDeerStalker** [comment]
done
