### ISSUE TITLE
Fuel tank's resource amount is not initialized to the saved value. (FuelSwitch)

### ISSUE THREAD

**Issue by yjchun** [sswelm/KSP-Interstellar-Extended#673]
KSP 1.11.2 (lastest)
FuelSwitch: 3.27 (lastest)

Symptoms: In VAB, when loading a craft, fuel tank's resource amount is not initialized to the saved value. Fuel tank is always full.

Save:
![20210326041711_1](https://user-images.githubusercontent.com/210884/112532453-2eafbf00-8dec-11eb-9ab6-8815875e6b2a.jpg)

After reloading craft:
![20210326041722_1](https://user-images.githubusercontent.com/210884/112532503-3d967180-8dec-11eb-988d-bc047a70bde1.jpg)

Reloading same craft Without InterstellarFuelSwitch:
![20210326044515_1](https://user-images.githubusercontent.com/210884/112534142-12148680-8dee-11eb-8ab2-3117ac08a2e0.jpg)

When I remove InterstellarFuelSwitch mod from GameData, this problem is not happening.
Can you check what is wrong?
Thanks.

**Comment by sswelm** [comment]
Alright, its fixed in IFS 3.28.0

**Comment by yjchun** [comment]
OK. Thank you.
