### ISSUE TITLE
LqdMethane + Oxidizer LFO Mixture Not Supported

### ISSUE THREAD

**Issue by SandGrains** [sswelm/KSP-Interstellar-Extended#674]
Cryogenic Engines mod adds LqdMethane + Oxidizer engines. There is currently no LFO Mixture resource defined with InterstellarFuelSwitch of MethaOxi for these engines, only LqdMethane + LqdOxygen is defined.

![image](https://user-images.githubusercontent.com/17347132/113808997-c00d2280-9756-11eb-9e6c-6dff2640fd4f.png)

**Comment by IGotCurbstomped** [comment]
Were you able to find a patch for this anywhere?

**Comment by sswelm** [comment]
Ok, I will add it in a 3: 1 ratio, just like in Cryo Engines

**Comment by sswelm** [comment]
It implemented
