### ISSUE TITLE
Computer parts with AI module cause log spam and severe Lag

### ISSUE THREAD

**Issue by flyguybc** [sswelm/KSP-Interstellar-Extended#679]
Any craft I create with AI (Computer Core, Kerbstein adapter, etc) eventually create a log spam of Packing/Unpacking the vessel.  The lag is severe enough to drop frames into the single digits and make the mod unplayable.
[KSPComputer Core.log](https://github.com/sswelm/KSP-Interstellar-Extended/files/6314576/KSPComputer.Core.log)
[KSPKerbstein.log](https://github.com/sswelm/KSP-Interstellar-Extended/files/6314577/KSPKerbstein.log)
[Test AI Kerbstein.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/6314579/Test.AI.Kerbstein.txt)
[Test AI.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/6314580/Test.AI.txt)

Attached are the logs of each test, and the craft file which I had to change to a .txt to upload here.

KSP 1.11.12.3077 - KSPIE 1.27.4

Steps to recreate:
Launch Craft
Ctrl Alt F12 - set orbit to 750000 above kerbin (this places you at 150km
Point prograde (SAS or no SAS either still causes problem)
Set engine to full burn.  
Time warp to 350km to 700km and cut engine.
Check Console and you should see repeating log spam

[Mod List.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/6314600/Mod.List.txt)

**Comment by sswelm** [comment]
Fixed in 1.28
