### ISSUE TITLE
Science Laboratory  NullReferenceException spam

### ISSUE THREAD

**Issue by melandor0** [sswelm/KSP-Interstellar-Extended#680]
The Science Laboratory (file name "scienceModule") part spams the error log with "exception: NullReferenceException: Object reference not set to an instance of an object", which shows up in KSP.log as:

```
[EXC 23:30:46.400] NullReferenceException: Object reference not set to an instance of an object
	FNPlugin.Refinery.InterstellarRefineryController.Update () (at <d375857bd79f4f6682e51f45757982d6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

Commenting out the refinery module from [part.cfg](https://github.com/sswelm/KSP-Interstellar-Extended/blob/1d5edfbb7de3f9f35e91dff65cb63e6f6249366b/GameData/WarpPlugin/Parts/Command/scienceModule/part.cfg#L99) (line 99-103) makes the errors go away.

```
//	MODULE
//	{
//		name = NuclearRefineryController
//		refineryType = 0
//	}
```

Steps to reproduce:
1. Make a craft with the "Science Laboratory" part
2. Launch 
3. Open the Console (Alt-F12)
4. The console will be filled with red error messages, once per tick or so, and KSP.log will have them as well.

Tested on KSP 1.11.2 with the following mods active (installed through CKAN):
Click Through Blocker
Community Resource Pack
Community Tech Tree
Interstellar Fuel Switch
Interstellar Fuel Switch Core
KSP Interstellar Extended
KSP Recall
Module Manager
Patch Manager
Toolbar Controller
TweakScale - Rescale Everything!
Zero MiniAVC

**Comment by sswelm** [comment]
ok, it will be fixed in 1.28.2
