### ISSUE TITLE
Plugins folder missing from 1.28.7 release

### ISSUE THREAD

**Issue by HebaruSan** [sswelm/KSP-Interstellar-Extended#682]
Hi @sswelm,

As far as I can tell, these files are still supposed to be part of the mod:

https://github.com/sswelm/KSP-Interstellar-Extended/tree/master/GameData/WarpPlugin/Plugins

But they're not in the ZIP:

![image](https://user-images.githubusercontent.com/1559108/118190785-38779b00-b409-11eb-80d3-2f9d8249f601.png)

I'm guessing this will mean a fresh install of this mod won't work, but if it was installed over the previous version, it would at least have _a_ DLL.

**Comment by HebaruSan** [comment]
FYI, there may be a few other things missing as well, since the download size dropped by about 40 MB:

![image](https://user-images.githubusercontent.com/1559108/118303381-ff900280-b4aa-11eb-9251-29d01827727b.png)

... but the plugin folder happened to be what caught my attention.

**Comment by sswelm** [comment]
weird, where did you download the zip from, they are in the original 1.28.7 zip file

**Comment by HebaruSan** [comment]
I got the file from SpaceDock:

- https://spacedock.info/content/FreeThinker_517/KSP_Interstellar_Extended/KSP_Interstellar_Extended-1.28.7.zip

Re-downloading, I get the same result. There are plugin folders for some of the bundled dependencies, but not WarpPlugin. I tried pasting the file listing here in a collapsed section, but it went over GitHub's character limit.

**Comment by sswelm** [comment]
are you sure you are looking insite the KSP_Interstellar_Extended-1.28.7.zip\GameData\WarpPlugin folder, when I download it it can clealy see 6 files and 7 sub folders

**Comment by HebaruSan** [comment]
> it can clealy see 6 files and 7 sub folders

There should be **8 sub folders**, including one called "Plugin". That's what's missing.

**Comment by HebaruSan** [comment]
(In case you're wondering why you're not inundated with forum bug reports about this yet, CKAN's bot has mercifully not indexed this version yet, because of the missing files. It's not a specific check, though, we just got lucky with how the version files are handled.)

**Comment by sswelm** [comment]
not sure what went wrong but I released 1.28.8.

**Comment by HebaruSan** [comment]
Looks good now, thanks for the fix!
