### ISSUE TITLE
Integration patches do not delete stock resources after adding InterstellarFuelSwitch

### ISSUE THREAD

**Issue by Gordon-Dry** [sswelm/KSP-Interstellar-Extended#695]
Is this forgotten?
Is there a reason?

Some mod's patches looking for stock resources add ModuleB9PartSwitch then and the confusion begins.
Or other weird circumstances.

Related to:
```
GameData\InterstellarFuelSwitch\PatchManager\ActiveMMPatches\IntegrationLiquidFuel.cfg
GameData\InterstellarFuelSwitch\PatchManager\ActiveMMPatches\IntegrationLiquidFuelOxidizer.cfg
GameData\InterstellarFuelSwitch\PatchManager\ActiveMMPatches\IntegrationOxygen.cfg
GameData\InterstellarFuelSwitch\PatchManager\ActiveMMPatches\IntegrationXenon.cfg
```

I need to check out how KSP behaves when I prune those 4 configs with PatchManager.

**Comment by sswelm** [comment]
well I haven't change anything so it s more likely  it is related to Module Manager

**Comment by Gordon-Dry** [comment]
I didn't mention a change - so I guess it was always like that.

**Comment by sswelm** [comment]
Well the idea is that you only remove the resource in the VAB and it won't modify them when loaded in flight. THat way you won't accidently cause a problem.

**Comment by Gordon-Dry** [comment]
Allright, I grasp that.
