### ISSUE TITLE
Science Laboratory generates no science

### ISSUE THREAD

**Issue by the-emerald** [sswelm/KSP-Interstellar-Extended#7]
KSP version: 1.2pre
KSPI Extended version: https://kerbal.curseforge.com/projects/ksp-interstellar-extended/files/2335476

The Science Laboratory does not generate any science, even though my labs are fully manned and have enough power. See attached for an example. It appears to happen everywhere, I have tested this in orbit around every body at different heights and none of them generate science.

![kerbal space program 10 10 2016 - 23 02 10 13](https://cloud.githubusercontent.com/assets/12746683/19242099/4976fcf0-8f44-11e6-8cd8-fac304f097b3.png)

**Comment by sswelm** [comment]
Is it fully powered? It needs Megajoules of power! Without it supply will not do anything

**Comment by suclearnub** [comment]
Turns out I only have enough power for one science lab, but even after turning one off, there is still no science generated. The lab also appears to consume no power.

![capture](https://cloud.githubusercontent.com/assets/12746683/19257170/0c9d8856-8fa0-11e6-80e9-a3e86cd5c949.PNG)

**Comment by sswelm** [comment]
I will investigate

**Comment by suclearnub** [comment]
It appears that it works in the Mobile Processing Lab after I "feed" it experiments.

![kerbal space program 10 18 2016 - 23 11 22 103](https://cloud.githubusercontent.com/assets/12746683/19483930/6fb01bdc-9588-11e6-8cdc-59ebe0cb8e53.png)

**Comment by sswelm** [comment]
Please verify if of they last release made any difference

**Comment by azhmur** [comment]
Same for me in 1.12.7. It doesn't require power and doesn't produce any science. Scientiests are in and reactor and generator are also present. Can't attach screenshot as far as amazon S3 seems to be down right now.

PS How KSP mods are being debugged?

**Comment by suclearnub** [comment]
@azhmur I believe that I solved it by realizing that I needed to feed it experiments.

**Comment by azhmur** [comment]
@suclearnub, sorry, i still don't get. You have two Science Laboratory (KSPI-E) on first screenshot, and Mobile Processing Lab (Squad) on second one. MPL should be fed with experiments (as it is stated in official documentation), but there is no such requirement on Science Laboratory in KSPI-E documentation.

![u2](https://cloud.githubusercontent.com/assets/2143587/23447305/17ce1cf2-fe5b-11e6-8f7b-6f7425df7382.jpg)
