### ISSUE TITLE
VARIES produces solid hydrogen while running

### ISSUE THREAD

**Issue by Cholerix** [sswelm/KSP-Interstellar-Extended#701]
The VARIES Antimatter Catalyzed Fusion Drive produces 1.71 units of solid hydrogen per second while running, resulting in a gain of 0.02 units per second.

This is caused by the method `InterstellarReactor.UseProductForPropulsion`, which seems to be missing a step: Instead of giving back some propellant, it gives back all of the propellant.

How is this supposed to work? I can create a pull request once I know how to fix it.

**Comment by Cholerix** [comment]
I think I figured it out. Pull request is open

**Comment by sswelm** [comment]
the idea is to give back the mass of the fusion product, so it can be used for propulsion. This is especially important for pure fusion mode where the engine is supposed to run on fusion products. The plan was to use the new resource, Charged Particle which now has a mass , so it can be used by ModuleEngine to generate force.
