### ISSUE TITLE
FuelSwitch: DropTanks have RSS fuels, but not LFO

### ISSUE THREAD

**Issue by NCommander** [sswelm/KSP-Interstellar-Extended#72]
Noticed this when building a SSTO. The droptanks are listed in the editor, but I can't but LFO or any of the stock fuels in it. Looks like a config problem but I can't figure out what has to be edited to fix it.

**Comment by sswelm** [comment]
what about now?

**Comment by arivaldh** [comment]
It seems that DropTanks do now have LiquidFuel and LiquidFuel + Oxidizer switchables.
I believe we can close it now.
