### ISSUE TITLE
Universal Liquidificator is not liquifying

### ISSUE THREAD

**Issue by LastStarDust** [sswelm/KSP-Interstellar-Extended#75]
Hello!
After some months of absence from the KSP world I am testing some new (to me) features of KSPI.
I bumped into this little (bug?). The Universal Liquidificator and the Universal Gasifier should be complementary to each other but they seem to behave the same way. They both act as gasifiers.
[I created a small video to illustrate this behavior.](https://www.dropbox.com/s/e38x4bbdnoqdyub/Bug_Report.mp4?dl=0)
I have attached a log file too.
Thank you for this wonderful mod and keep up the good work.
[output_log.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/1197769/output_log.txt)

**Comment by sswelm** [comment]
thanks, I will fix it next release
