### ISSUE TITLE
Refrigerator has duplicate slots

### ISSUE THREAD

**Issue by LastStarDust** [sswelm/KSP-Interstellar-Extended#76]
Hello
my testing is continuing. I noticed that the refrigerator has duplicate slots for each and every gas.
![screenshot](https://user-images.githubusercontent.com/8758474/28993252-806c4e14-79b2-11e7-9ea4-b42f89634667.png)
If you fiddle with both at the same time there are unpredictable results.
[output_log.txt](https://github.com/sswelm/KSP-Interstellar-Extended/files/1202143/output_log.txt)

**Comment by sswelm** [comment]
Thanks for reporting, I removed doubles
