### ISSUE TITLE
Some strange numbers with methalox and some tanks

### ISSUE THREAD

**Issue by Khalkion** [sswelm/KSP-Interstellar-Extended#78]
I've found some strange numbers with methalox and some tanks.

WarpPlugin\Parts\FuelTank\InterstellarFuelTank\InterstellarFuelTank-X200-48.cfg
tankSwitchNames = LFO;LiquidFuel;Hydrogen;Hydrolox;Methalox;D+He3;Oxygen;Methane;Ammonia;Hydrazine;Nitrogen;CO2;CO;Water;HTP;Argon
resourceAmounts = 3024,3696;6720;26880;21504,5376;**14972.16,10632**;13440,13440;**11907.84**;26880;26880;26880;26880;26880;26880;26880;26880

I think it should be

resourceAmounts = 3024,3696;6720;26880;21504,5376;**14927.6,11872.4**;13440,13440;**26880**;26880;26880;26880;26880;26880;26880;26880;26880
to preserve 0.557:0.443 ratio of methalox and to fill tank with pure oxygen.

WarpPlugin\Parts\FuelTank\InterstellarFuelTank\InterstellarFuelTank-X200-32.cfg

resourceAmounts = 1555.2,1900.8;3456;17280;13824,3456;**9625,8424**;8640,8640;17280;17280;17280;17280;17280;17280;17280;17280;17280;17280

resourceAmounts = 1555.2,1900.8;3456;17280;13824,3456;**9625,7655**;8640,8640;17280;17280;17280;17280;17280;17280;17280;17280;17280;17280

WarpPlugin\Parts\FuelTank\NBconeTank3m\part.cfg

resourceAmounts = 2160,2640;4800;24000;19200,4800;**13368,11700**;12000,12000;24000;24000;24000;24000;24000;24000;24000;24000;24000

resourceAmounts = 2160,2640;4800;24000;19200,4800;**13368,10632**;12000,12000;24000;24000;24000;24000;24000;24000;24000;24000;24000

Also I'm not sure about D+He3 quantites. Looks like Daedalus engine uses 0.194976:0.805024 ratio. But most of the tanks have 1:1 ratio for this option with the exception of InterstellarFuelTank-X200-96, which has the same ratio as Daedalus engine.

**Comment by sswelm** [comment]
Alright, integrated your suggestions. Regarding the D+He3 I', not sure yet what to do. I'm opting of removing it completely as Liquid Helium3 is extremely hard to store. The specialized cryogenic tanks make more sense.
