### ISSUE TITLE
Some parts are messed up

### ISSUE THREAD

**Issue by Plnda** [sswelm/KSP-Interstellar-Extended#81]
Clean install of KSP 1.3 with this mod 1.15.0.7. Configuring a hydrogen tank with a timberwind engine will warp me into space on load, Also I get Nan values for thermal power (side note I'm running this in OSX). Also I'm not able to run a configuration with Reactor -> Thermal Nozzle, I just cannot get trust

**Comment by sswelm** [comment]
please updated CRP to 0.7.2 or install latest patch KSPI 1.15.0.8
