### ISSUE TITLE
Megajoules and EC capacity of a generator goes to zero when it is disabled manually

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#83]
Steps to reproduce: 

1. Launch a vessel with a generator attached
2. Disable generator in the right click context menu
3. Watch as the stored charge / megajoules as well as the indicated storage capacity goes to 0.00

**Comment by sswelm** [comment]
This is intended behavior. The power represent a very temperal buffer to overcome any unbalances, especially during time warp acceleration, it's not a persistent form of energy

**Comment by alismatales** [comment]
It reads "0.00 / 0.00" in the UI and stays that way after activating the generator again. 

I cant imagine this is working quite the way it should?

**Comment by sswelm** [comment]
After successfully activating, it should restore itself back to former buffer. If that isn't the case, it would be a bug

**Comment by alismatales** [comment]
> After successfully activating, it should restore itself back to former buffer.

Apparently it does, sometimes, but not always. I didnt do enough testing to pinpoint if there is some pattern. 

Quickloading or Reloading vessel (going to tracking station and back) fixes it though. 

Not the most pressing issue i guess. Maybe i'll look into it..
