### ISSUE TITLE
Liquid Hex Tank has some resources mixed up

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#84]
If you select  /  This resouces is added to the tank:

Deuterium   -> HTP 
HeavyWater -> Water
Helium-3 -> LqdDeuterium
Helium-4 -> LqdHe3

**Comment by sswelm** [comment]
Liquid Hex Tank?

**Comment by sswelm** [comment]
Ok fixed for next release
