### ISSUE TITLE
KSPIE drills extremely slow

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#85]
I tracked this issue down to this code: 

https://github.com/sswelm/KSP-Interstellar-Extended/blob/7b22a5d9c2e9a0bf67f0263c3f67f235f904ce14/FNPlugin/Collectors/UniversalCrustExtractor.cs#L596-L597

(As well as further above in 585 and 586)

"abundance" is a decimal percentage (and therefore never larger than 1), and exponentiating that with the power of 4 makes it extremely small. 

I dont quite understand what this bit of code was supposed to do, but i believe it can simply be removed, that gives the universal drill the same mining speed as a stock drill.

**Comment by sswelm** [comment]
Nope this is intentional, it is a way to create very low densities functional because the stock resource system does not allow densities below 0.001, which is not low enough

see alsi

https://forum.kerbalspaceprogram.com/index.php?/topic/83007-13-community-resource-pack/&do=findComment&comment=2961550

but I should probably replace the four by a 3

**Comment by sswelm** [comment]
The general idea is to make trace amount of rare resource available are density that make it not vey worthwhile. For example Uranium is technically everywhere in the ground, it just in such low denisties that you would be crazy to mine it.

**Comment by alismatales** [comment]
No offense, but do you even play KSP with your own mod? 

` if (abundance < 1) `

does not make sense in this context since abundance is a decimal percentage - _it is always less than one_ - a abundance of, say, 4,3% is reported as 0,043 - exponentiate that to the power of 4 and you get a value of 0,000000341.
The universal drill then takes that  0,000000341 and calculates the mined amount which is ridiculously low even for relatively high abundances. 

The stock drill is thousands of times faster than the universal drill in the current state.

**Comment by sswelm** [comment]
Always less than 1?  I was under the impression it could go up to 100

**Comment by alismatales** [comment]
Decimal percentages: 
1 = 100% 
0.1 = 10% 
0.05 = 5%

**Comment by alismatales** [comment]
I guess what you meant to write is 
`if (abundance < 0.01)`

in words "if the abundance is less than 1%"

**Comment by sswelm** [comment]
lol, my own code at FNMassSpectrometer appears to confirm what your say, because I multiply it bty 100 to convert it to a percentage. Good find!!

**Comment by sswelm** [comment]
http://i.imgur.com/Lecl2pt.png
