### ISSUE TITLE
Tri-Alpha Reactor has a misleading power rating

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#86]
The Tri-Alpha reactor is rated for 1, 1.5 and 2.25 GJ power at MK1, 2 and 3. 

It can never reach those values since all available fuel modes on the reactor have a NormalisedReactionRate  of less than 1.
Example: 

![](https://i.imgur.com/VDZRi3V.png)

But the best power rating you can get from the reactor is 1.87  instead of 2.25:

![](https://i.imgur.com/rwvPZY1.png)

**Comment by sswelm** [comment]
Ok, so the Mk1- Mk3 Power output listing in the  should list the maximum achievable power for that tech level

**Comment by alismatales** [comment]
This screenshot is from a sandbox game, so everything is unlocked. 

I'm not sure how you'd fix that though. The sourcecode looks up the maximum power rating (2.25) and applies the power multiplier of the fuel mode. Since the best fuel mode (proto-lithium7) has a multiplier of 0.83 you'll never get more than 1.87GW out of the reactor.

So you'd either have to introduce a fuel mode for that reactor with a multiplier of 1, or change where the  info boxes take their numbers from. 

By the way, i just noticed that the part info box displays the wrong power rating altogether.
Still a sandbox game, so fully upgraded, but it shows the mk1 rating:

![](https://i.imgur.com/0SsYlG9.png)

This also seems to affect all reactors.

**Comment by sswelm** [comment]
Indeed, we have to make all information consistent and add more helpful descriptions, which should make them more accessible to new people which often get confused by all the complexity
