### ISSUE TITLE
Wrong efficiency on nuclear engines

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#88]
Nuclear engines with an integrated thermal generator (Timberwind, Closed cycle gas core, direct cycle nuclear turbojet, solid core and TORY) have a maximum generator efficiency of 8% as per config file: 

efficiencyMk1 = 0.04
efficiencyMk2 = 0.06
efficiencyMk3 = 0.08

But show 32 or 64% in the editor description regardless. This is misleading. 

![](https://i.imgur.com/5q8uytC.png)

**Comment by sswelm** [comment]
I can see this is confusing. It is still using some old numbers
